### ISSUE TITLE
castlabs electron version is missing the typescript .d.ts file

### ISSUE THREAD

**Issue by andymartinwork** [castlabs/electron-releases#1]
Run a standard electron-quick-start app, and npm install it.

Look inside node_modules/electron

notice the electron.d.ts file.

Removing this makes it significantly harder to "plug and play" the swap out of electron, as now my app will not compile into javascript.

**Comment by khwaaj** [comment]
Good catch, thanks for reporting it.

This is simply an oversight on our part. I'll make sure it gets fixed.

**Comment by khwaaj** [comment]
The release has been updated and now electron.d.ts is part of the install.
