### ISSUE TITLE
Twitter doesn't load?

### ISSUE THREAD

**Issue by alectrocute** [castlabs/electron-releases#102]
Is it just me, or does `https://twitter.com` refuse to load in a Webview? Any tips on getting this working? Thanks!

**Comment by khwaaj** [comment]
Which version of ECS are you using? Also, do you see the same problem in stock Electron?

I did a quick test with `v13.1.7-wvvmp` and `v14.0.0-wvvmp-beta.15`, and the front page seems to load find (although I don't have an account so I didn't log in).

**Comment by alectrocute** [comment]
I posted this issue too soon @khwaaj. I've discovered the solution for me, it wasn't specific to ECS. If anybody else runs into this issue, here's what worked:

```js
app.commandLine.appendSwitch('disable-features', 'CrossOriginOpenerPolicy')
```
