### ISSUE TITLE
Netflix won't work

### ISSUE THREAD

**Issue by Sinux-Project** [castlabs/electron-releases#103]
This is a issue that still occurs that I hope that can be fixed with electron.

The problem is inside the widefine support.

**Comment by khwaaj** [comment]
I'm going to need more information than that to be able to help you.

What I can tell you is that Netflix works fine here, as long as I production sign the ECS based application using [EVS](https://github.com/castlabs/electron-releases/wiki/EVS). If you do not properly sign your application for production commercial service, like Netflix, will not work.

**Comment by Sinux-Project** [comment]
Thanks you fixed my issue it was just EVS that was not installed.
