### ISSUE TITLE
Getting an error on build

### ISSUE THREAD

**Issue by Terroriser1** [castlabs/electron-releases#104]
When I use your electron build I am getting each time a build error. 

I will attach a screenshot with more information: 
![55a3epxx4](https://user-images.githubusercontent.com/35117713/126871336-8a2efaaf-a1f2-4fc2-86df-79884a91c1ae.png)

and the source code is available here: https://github.com/Terroriser1/Discord-Netflix

**Comment by Terroriser1** [comment]
Fixed by adding this to my package.json

 "electronVersion": "13.0.0",
    "electronDownload": {
      "version": "13.0.0-wvvmp",
      "mirror": "https://github.com/castlabs/electron-releases/releases/download/v"
    },
    
    Please describe this on your readme or somewhere else.

**Comment by khwaaj** [comment]
It is in the FAQ already: https://github.com/castlabs/electron-releases/wiki/FAQ#how-can-i-use-electron-builder-with-ecs
