### ISSUE TITLE
Urgent: Let's Encrypt root CA isn't working properly

### ISSUE THREAD

**Issue by olirehacek** [castlabs/electron-releases#107]
ref.: https://github.com/electron/electron/issues/31212

Solved in latest electron releases (13.5.1 , 14.1.0, 15.1.0). 

When can we please expect ECS update as our player is currently totally broken and can't call any API endpoints.

Thank You.

**Comment by khwaaj** [comment]
I'll try to speed this up as best I can and the first couple of releases will be published today, provided there are no unexpected problems. I hoping we can get all of them published before the end of the day tomorrow.

**Comment by khwaaj** [comment]
Quick update, the fixed versions for `v12`, `v13` and `v14` are now published, `v15` is still building but should be available in a few hours.

**Comment by khwaaj** [comment]
It took a bit longer than expected but now the fixed `v15` is also published. Let me know if there are any further issues!

**Comment by olirehacek** [comment]
**You guys are awesome, as always.**

Thank You very much !
