### ISSUE TITLE
Can't sign Hulu Native App: HTTP Error 400 Bad Request

### ISSUE THREAD

**Issue by PhantomNimbi** [castlabs/electron-releases#113]
Hello, I'm having an issue with a nativefied webapp. It only happens with this one service and it only recently started happening so wnated to make sure it wasn't a bug that popped back up in the latest update.

It's an issue that happened before but was fixed and now it seems to have returned. Here is the old post referring to it:

[Issue #82 - HTTPError: Signing request failed: 400 Bad Request](https://github.com/castlabs/electron-releases/issues/82)

I'm sure it's not the same cause as before since the same format works for my HBO Max, Netflix Spotidy Webplayer and Amazon Prime Video apps and previously worked for my Hulu app. But I recently redid my Hulu script and now even after reverting changes it now refuses to accept the digital signature.

Here is my sign script:

`sign-pkg.bat`
```cmd
@echo off
python -m castlabs_evs.vmp sign-pkg -p -f .
pause
```

I run the sign script from inside the nativefied app directory.

This is my nativefier script for my Hulu app:

`build-pkg.bat`

```cmd
@echo off
nativefier -n "Hulu" "https://www.hulu.com/" --tray "true" --verbose --enable-es3-apis--widevine --single-instance --hide-window-frame --conceal --background-color "#333333" --internal-urls ".*(hulu)\.(com).*" --user-agent firefox --icon "res/icon.ico"
pause
```

If anyone can look into this and see if there might be something that is causing this in the current castlabs_evs version I would much appreciate any help I can get. As it stands it seems like this is something that is only happening with Hulu right now.

I'm on Windows 11 Version 21H2 (OS Build 22000.282)

**Comment by khwaaj** [comment]
First let me venture a guess. The `build-pkg.bat` script you provided above appears to lack a space between the two options `--enable-es3-apis` and `--widevine`, i.e. `--enable-es3-apis--widevine`. Could this be the cause of the error?

Also, to help diagnose this kinds of errors, please be specific with the details of the versions of the components used (as well as the platform) and the error itself:
* The version of ECS used (e.g. `v13.6.1-wvvmp`)
* The version of the EVS client (e.g. execute `python3 -m castlabs_evs.vmp --version`)
* The complete error message you receive

Just saying *current version*, or even *latest version*, can be ambiguous and makes it more difficult to diagnose your issue.

**Comment by PhantomNimbi** [comment]
I can definitely check. I actually didn't notice the missing space. Give me a moment to try that and if it fixes it I'll let you know.

As for the other info I'll gra those while I'm testing.
