### ISSUE TITLE
Linux Arm64 Releases

### ISSUE THREAD

**Issue by coredev-uk** [castlabs/electron-releases#114]
Could releases for Linux-Arm64 be made? Just as they are on the normal Electron repo.

**Comment by khwaaj** [comment]
There is no official linux-arm64 Widevine CDM, which is why we are not providing this build. Since we can't get a CDM it would not provide anything beyond what a regular Electron release would anyway (see #23 & #87, for reference).

**Comment by coredev-uk** [comment]
Sorry for that, thanks for the reply.

**Comment by marcan** [comment]
FWIW, Widevine is available in Asahi Linux at `/usr/lib64/chromium-browser/WidevineCdm` (if the user has run the installer). This is not "official" but it is as close to it as we can get (we do not redistribute it unlike certain other distros, it is extracted directly from Lacros bundles downloaded from Google's public cloud bucket for ChromeOS sources). The binary is only minimally patched to make it compatible with vanilla arm64 glibc (no changes to CDM code, just changes to ELF structure similar to what `patchelf` does). We expect any Chromium-based apps that want to make use of Widevine to search for it in that path on our systems.
