### ISSUE TITLE
`python3 -m castlabs_evs.account reauth` return `TypeError: 'str' object is not callable`

### ISSUE THREAD

**Issue by quanglam2807** [castlabs/electron-releases#115]
Recently, `python3 -m castlabs_evs.account reauth` occasionally (> 80%) returns `TypeError: 'str' object is not callable` when the command is run on GitHub Actions. Could there be something wrong with the server?

https://github.com/webcatalog/neutron/runs/4265919905?check_suite_focus=true

**Comment by quanglam2807** [comment]
Found the cause. Something in Python 3.9.8 breaks it. Downgrading 3.9.7 fixes the problem.

**Comment by khwaaj** [comment]
Thanks for the report. Interestingly I cannot reproduce this with python 3.9.9 on macOS, using version `1.1.0` of the EVS tools, but I'm not sure what version of the tools you were using?

It could also be something specific to `python 3.9.8` that caused the issue. This the `argparse` issue mentioned [here](https://www.python.org/downloads/release/python-399/) sounds like a good candidate.

Let me know if you encounter it again!

**Comment by quanglam2807** [comment]
Thank you, @khwaaj. I tested it with 3.9.7 and 3.10.0, and both worked so I think you're right, this bug only occurs with Python 3.9.8 (the current Python version of GitHub Actions and Homebrew)
