### ISSUE TITLE
Electron ver13.6.* support for macOS 10.11 and 10.12

### ISSUE THREAD

**Issue by shmulka** [castlabs/electron-releases#119]
App crashes when attempting to open a new window and autoplay a video on macOS 10.11 and 10.12. 

App built with [Electron version 13.6.2 ](https://github.com/castlabs/electron-releases/releases/tag/v13.6.2-wvvmp)and Widevine 4.10.2391.0 installed.
Does Electron/Castlabs ver13.6.* still support macOS 10.11 and 10.12?
Downgrading to [Electron ver13.5.2](https://github.com/castlabs/electron-releases/releases/tag/v13.5.2-wvvmp)  seems to have solved the issue.

Error displayed:

```
Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
```

**Comment by khwaaj** [comment]
I have not seen any official note that support was changed between `v13.5` and `v13.6`, so it should be working AFAICT. This might have something to do with an SDK mismatch on the builder though, so I'll look into that and see if I can find anything.

**Comment by khwaaj** [comment]
After some digging it looks like `v13.6.x` has been built with the `11.3` SDK, whereas the official builds are using `11.1`. I'm not sure if this is the cause of the issue here, but I'll make sure `v13.6.7` is built using the same SDK as the official builds.

`v13.6.7` should be published over the weekend.

**Comment by khwaaj** [comment]
`v13.6.7` was just [published](https://github.com/castlabs/electron-releases/releases/tag/v13.6.7-wvvmp). Please check it out and see if it fixes the issue you have been seeing.

**Comment by shmulka** [comment]
Good call on the SDK.
macOS `10.11` and `10.12` are now working as expected with `v13.6.7 ` - building with 11.1 seems to have solved the issue!

Many thanks!

**Comment by khwaaj** [comment]
These are the official SDKs fo the different versions AFAICT:

| Version | SDK |
| :---: |  :--- |
|`17` | 12.0 |
| `16`, `15`, `14` | 11.3 |
| `13` | 11.1 |
| `12`, `11` | 11.0 |
