### ISSUE TITLE
Mac build of v1.8.7-hdcp-vmp1010 fails Gatekeeper acceptance

### ISSUE THREAD

**Issue by simongregory** [castlabs/electron-releases#12]
During our build we use `spctl --ignore-cache --no-cache --assess --type execute "$APP_DIR"` to verify Gatekeeper will be ok with the release.

With v1.8.7-hdcp-vmp1010 this fails with `rejected (invalid destination for symbolic link in bundle)`. The link is `Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries/Libraries`, so it's easy to remove.

To be honest I don't know enough about Gatekeeper to be sure of the effect of leaving the link in the app bundle. It might mean users would have to lower the security level to allow apps downloaded from anywhere - but it might mean it's just not valid for the app store and not be relevant. 

This is more to document the issue than request a fix so please just close this unless you think I've missed something.

**Comment by khwaaj** [comment]
This again, it has happened before. I've never been able to reproduce it during a build though so I'm not sure what is causing it. I'll fix the package and update it, for starters.

I'll let you know once it is up.

**Comment by khwaaj** [comment]
The package has been updated, if you want to use the new build make sure to clear your electron-downloader caches.

I'll make another attempt to prevent these in the future, but since it appears to happen intermittently the cause is elusive.

**Comment by khwaaj** [comment]
I got lucky and came upon what is almost certainly the cause of this, so we should not be seeing this in future releases.
