### ISSUE TITLE
Error getting response from license server.

### ISSUE THREAD

**Issue by matgott** [castlabs/electron-releases#124]
Hi, I have a website perfectly working (single .html) with shaka-player. Now  I wanted to use electron with it.

But when shaka make the request to the license server, the requests fail. It is something that I missing? (If I open my web standalone, works well).

My main.js:
```
const {app, components, BrowserWindow} = require('electron')
const path = require('path')

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      preload: path.join(__dirname, 'preload.js'),
      plugins: true
    }
  })

  const startFile = path.join(__dirname, '/src/index.html');

  mainWindow.loadFile(startFile);
  mainWindow.webContents.openDevTools()
}

app.whenReady().then(async () => {
  await components.whenReady();
  console.log('components ready:', components.status());

  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

The license server returns ACCESS_DENIED which means that the payload that I'm sending is wrong (the problem is that shaka do that, and its the same for the web and electron).

**Comment by khwaaj** [comment]
Hi,

Are you trying to stream production assets? If so, you will need to VMP re-sign ECS for production. The published builds are only pre-signed for development, so this would be my fist guess at what is causing your issues.

You can re-sign you application using our free VMP signing service, [EVS](https://github.com/castlabs/electron-releases/wiki/EVS). There may also be some helpful hints in the [FAQ](https://github.com/castlabs/electron-releases/wiki/FAQ), or among the previously closed tickets, depending on exactly what you are doing.

**Comment by matgott** [comment]
Hi khwaaj, ty for answering.

Tbh I', not familiar with the VMP part. I receive an URL that is the license server and that's all.

If I run my website alone (without electron) it works well. Is this something specific for this package?

**Comment by khwaaj** [comment]
VMP, Verified Media Path, is a Widevine technology that is used to certify the integrity of the media path for an application. ECS is certified, but for various reasons we cannot pre-sign ECS for production use, e.g. if you want to be able to stream DRM assets from commercial services like HBO or Netflix.

EVS allows you to register an account and production sign your ECS based application yourself, making it possible to use with commercial services. This is usually enough to make Widevine work, but some services may also employ further checks (like User-Agent enforcement). I'm not sure exactly what you are trying to stream here, but my guess is that this is your issue (it is, by far, the most common problem for new users).

**Comment by matgott** [comment]
Thanks for the explanation! very useful.
I created my account, do I need to sign my app now? (its not builded, I'm working on it and and run it with npm start)

**Comment by khwaaj** [comment]
Just saw your comment about registering an account, did you also execute the signing step?

Depending on how you start and/or package your application you will also need to do this a bit differently. All of this is documented in the links I've already provided. If you are not packaging you probably just want to do what is described in [this FAQ entry](https://github.com/castlabs/electron-releases/wiki/FAQ#how-can-i-vmp-sign-my-application-during-development).

**Comment by matgott** [comment]
Damn, I missed the FAQ link. Thank you!

Last question (I promise). DOCS says that we need to refresh the tokens. Once we sign a builded app, do we need to refersh and rebuild the app every time?

**Comment by khwaaj** [comment]
No, this is mostly targeted at CI integrations. If you just execute the signing manually the tool will ask you for credentials in case the authorization token has expired.

When you integrate this with packaging, e.g. using `electron-builder`, you may need to get a bit more advanced.

**Comment by matgott** [comment]
Gotcha.

I logged with the account but I get Signature Invalid:

```
python -m castlabs_evs.vmp sign-pkg node_modules\electron\dist
Signing: node_modules\electron\dist\electron.exe
 - Verifying existing VMP signature
 - Signature invalid: Certificate is valid for development only
 - Requesting VMP signature
```

**Comment by khwaaj** [comment]
This is just the signature that already exists, that is why it is "Requesting VMP singature" right after. Once the tool completes you should have a valid signature. To check, you can use the same command but with `verify-pkg` instead of `sign-pkg`.

**Comment by matgott** [comment]
omg! It's working! You're so cool khwaaj thanks for all your help.

This was very instructive.

**Comment by ryankashi** [comment]
@matgott I am quite unfamiliar with how Widevine license servers work. Could you please explain?

Specifically, I am trying to implement a Shaka player natively inside of my electron app using .mpd files as the source, however I am confused regarding how to link my Castlabs Widevine License to the DRM source for the shaka player?

**Comment by matgott** [comment]
> com.widevine.alpha

Hi ryan. The value for the com.widevine.alpha input is the license server url. I'm not the responsible for that, I just received that with the .mpd urls to use.

**Comment by ryankashi** [comment]
Oh, I see! So each .mpd I receive will have its own com.widevine.alpha source associated with it? How do I go about receiving this com.widevine.alpha source after a user has been authorized correctly?

**Comment by matgott** [comment]
> 

It depends. I have a licenseUrl for each .mpd (but in my case all are the same).

**Comment by matgott** [comment]
@khwaaj I'm trying to sign the app builded and fails:

```
python -m castlabs_evs.vmp sign-pkg dist
 - Verifying existing VMP signature
 - Signature invalid: Failed to read signature
 - Requesting VMP signature
HTTPError: Signing request failed: 400 Bad Request
 <- ValidityError: Binary signature denied
```

**Comment by khwaaj** [comment]
You get `Binary signature denied` when the binary image you are trying to sign is not an ECS release. If you are using `electron-builder` it is probably downloading a regular Electron release for packaging, which would cause this error.

Check out [this FAQ entry](https://github.com/castlabs/electron-releases/wiki/FAQ#how-can-i-use-electron-builder-with-ecs).

**Comment by ryankashi** [comment]
@matgott Do you have to play your videos from a secure https:// or localhost:// location? or are you able to play your videos via the file:// specification?

I am currently getting error 6001 via the test video:
`https://d24rwxnt7vw9qb.cloudfront.net/v1/dash/e6d234965645b411ad572802b6c9d5a10799c9c1/All_Reference_Streams/2fc23947945841b9b1be9768f9c13e75/index.mpd`

With setting:

`player.configure({
			drm: {
				servers: {
					'com.widevine.alpha': 'https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/?specConform=true'
				}
			}
		});`

Also if you use electron-forge to package I can try to help with that

**Comment by matgott** [comment]
> 

localhost or https work for me.

But if you are using electron you need to do that EVS signing that khwaaj exaplained to me

**Comment by ryankashi** [comment]
Yes, I am far more familiar with Electron/EVS than I am with Shaka. Could you send me a "hello world" that works inside of electron, with a shaka player running from file://?

Or are you spinning up your own server inside of electron and loading from localhost:// for it?

Essentially I am quite confused how I can run a video inside of Shaka Player via a webpage I load through electron via app.loadFile

**Comment by matgott** [comment]
> 

I don't have any code because it is the same code that you share. But you need to use this: https://github.com/castlabs/electron-releases/wiki/EVS

Signing first in development mode as explains here: https://github.com/castlabs/electron-releases/wiki/FAQ#how-can-i-use-electron-builder-with-ecs

**Comment by matgott** [comment]
Hi @khwaaj , its me again, sorry.  I'm trying to sign a production build for windows.

My dist folder has inside the .exe and a win-unpackage folder. Which path should I use for signing? dist or win-unpackage?

dist throw me the binary error
win-unpackage sign without problem but my app doesn't work.

**Comment by khwaaj** [comment]
I'm not familiar with all packaging options that `electron-builder` provides, but generally you would need to execute the VMP signing in the `afterPack`/`afterSign` hooks (depending on the platform), and you would sign the `appOutDir` directory. [This comment](https://github.com/castlabs/electron-releases/issues/121#issuecomment-1017683065) could be a good place to start, but there are several other older issues discussing this as well.

**Comment by matgott** [comment]
> I'm not familiar with all packaging options that `electron-builder` provides, but generally you would need to execute the VMP signing in the `afterPack`/`afterSign` hooks (depending on the platform), and you would sign the `appOutDir` directory. [This comment](https://github.com/castlabs/electron-releases/issues/121#issuecomment-1017683065) could be a good place to start, but there are several other older issues discussing this as well.

Yeah, I did it afterPack with outDir and it signed but my app it's not working.

Before I generated a portable version for windows and without the sign it worked. Now I'm generating a nsis version, with the sign and the app doesn't work.

**Comment by matgott** [comment]
Update: electron-builder generate the package first and then sign it.

After that generates an installer for my app.

If I run the .exe in the package folder my app works and my streaming start.
If I run the installer and install the program and run it, my straming fails.

**Comment by khwaaj** [comment]
Is the `electron.exe.sig` file included in the installer? And what is the output of `verify-pkg` if you run it on the installed version of the program?

Also, in case you are using portable NSIS format (i.e. self extracting and executing), there have been some [known issues](https://github.com/castlabs/electron-releases/issues/56#issuecomment-847588205) around that.

**Comment by matgott** [comment]
That works. Ty ty ty ty!!!

**Comment by khwaaj** [comment]
I guess we can close this, please reopen if you feel differently!
