### ISSUE TITLE
Response code 404 (Not Found), while installing any version in existing project.

### ISSUE THREAD

**Issue by ChaitanyaLKulkarni** [castlabs/electron-releases#125]
While installing any version of castlabs electron in existing project, I am getting this error in postinstall script

`HTTPError: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v18.0.2/electron-v18.0.2-win32-x64.zip`

this is how I am trying to install:
`npm install "https://github.com/castlabs/electron-releases#v18.0.2+wvcus" --save-dev`

logs:
```
PS F:\Projects\NodeJs\SpotifyController> 

> electron@18.0.2 postinstall F:\Projects\NodeJs\SpotifyController\node_modules\electron
> node install.js

HTTPError: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v18.0.2/electron-v18.0.2-win32-x64.zip
    at EventEmitter.<anonymous> (F:\Projects\NodeJs\SpotifyController\node_modules\got\source\as-stream.js:35:24)
    at EventEmitter.emit (events.js:315:20)
    at module.exports (F:\Projects\NodeJs\SpotifyController\node_modules\got\source\get-response.js:22:10)
    at ClientRequest.handleResponse (F:\Projects\NodeJs\SpotifyController\node_modules\got\source\request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (F:\Projects\NodeJs\SpotifyController\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
npm WARN @apideck/better-ajv-errors@0.3.1 requires a peer of ajv@>=8 but none is installed. You must install peer dependencies yourself.
npm WARN fork-ts-checker-webpack-plugin@6.5.0 requires a peer of typescript@>= 2.7 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN spotifycontroller@1.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dmg-license@1.0.10 (node_modules\dmg-license):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for dmg-license@1.0.10: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@18.0.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@18.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Thank you!

**Comment by khwaaj** [comment]
Something is wrong with the request, it lacks the `+wvcus` part of the name. I suspect there could be some conflict in your `package.json`, or something similar?

**Comment by khwaaj** [comment]
Also, which `npm` version are you on? I believe some older version had problems with `+` in the URLs.

**Comment by ChaitanyaLKulkarni** [comment]
> Something is wrong with the request, it lacks the `+wvcus` part of the name. I suspect there could be some conflict in your `package.json`, or something similar?

Thank you for quick reply.
I was using normal electron v16.0.5 previously but, I uninstalled it and then tried still no luck.
Should I clean and then install all dependencied?

Here is my package.json file:
```
{
    "main": "public/electron.js",
    "homepage": "./",
    "build": {
        "buildDependenciesFromSource": true,
        "win": {
            "publish": "github"
        }
    },
    "dependencies": {
        "axios": "^0.24.0",
        "electron-deeplink": "^1.0.9",
        "electron-is-dev": "^2.0.0",
        "electron-log": "^4.4.3",
        "electron-store": "^8.0.1",
        "electron-updater": "^4.6.1",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-router-dom": "^6.1.1",
        "react-scripts": "5.0.0",
        "robotjs": "^0.6.0",
    },
    "devDependencies": {
        "concurrently": "^6.5.0",
        "cross-env": "^7.0.3",
        "electron-builder": "^22.14.5",
        "wait-on": "^6.0.0"
    },
    "scripts": {
        "react-start": "react-scripts start",
        "react-build": "react-scripts build",
        "react-test": "react-scripts test --env=jsdom",
        "react-eject": "react-scripts eject",
        "electron-build": "electron-builder",
        "release": "npm run react-build && electron-builder --publish=always",
        "build": "npm run react-build && npm run electron-build",
        "start": "concurrently \"cross-env BROWSER=none npm run react-start\" \"wait-on http://localhost:3000 && electron .\"",
        "rebuild": "npm rebuild --runtime=electron --target=16.0.5 --disturl=https://atom.io/download/atom-shell --abi=93"
    },
    "eslintConfig": {
        "extends": [
            "react-app",
            "react-app/jest"
        ]
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    }
}

```

**Comment by ChaitanyaLKulkarni** [comment]
> Also, which `npm` version are you on? I believe some older version had problems with `+` in the URLs (you could try Ising `%2B` instead).

My node and npm version:

node -v
v14.16.1

npm -v
6.14.12

**Comment by khwaaj** [comment]
You can just remove `node_modules/electron` and make sure that you have an entry in `devDependencies` that look like this:

```
"electron": "github:castlabs/electron-releases#v18.0.2+wvcus"
```

Then try to install. Since you are using `electron-builder` you also need some additional things when you package your app, see [this FAQ](https://github.com/castlabs/electron-releases/wiki/FAQ#how-can-i-use-electron-builder-with-ecs).

**Comment by ChaitanyaLKulkarni** [comment]
> You can just remove `node_modules/electron` and make sure that you have an entry in `devDependencies` that look like this:
> 
> ```
> "electron": "github:castlabs/electron-releases#v18.0.2+wvcus"
> ```
> 
> Then try to install. Since you are using `electron-builder` you also need some additional things when you package your app, see [this FAQ](https://github.com/castlabs/electron-releases/wiki/FAQ#how-can-i-use-electron-builder-with-ecs).

There was no `node_modules/electron` as I uninstalled previous electron. I also tried to install it in new blank project still getting same result.

same error is there when i try to change package.json manully and then `npm intall`

**Comment by khwaaj** [comment]
That is very strange, it works fine in my test projects albeit with `npm 7.24.2`/`node 16.14.0`. What does the `version` entry in `node_modules/electron/package.json` say?

**Comment by ChaitanyaLKulkarni** [comment]
Updating to current version of nodejs `v17.8.0` worked, now I am able to install it without problem.

But still i am confused why was it happening cause it tried putting `+` in my version in package.json and wrote a script that prints it and it was printing it correctly.

Thank for the help.
