### ISSUE TITLE
[typo] `uppdatesEnabled` should `updatesEnabled` ?

### ISSUE THREAD

**Issue by et84121** [castlabs/electron-releases#129]
as title

https://github.com/castlabs/electron-releases/blob/d11f8398609983b287b0f7e38451f3f142a3ed9b/electron.d.ts#L3669

**Comment by khwaaj** [comment]
Good catch, this typo is actually present in versions 17-19. I've made the relevant fix, so it will roll out with the next release for each of the respective release series.

Thanks for the report!

**Comment by et84121** [comment]
thank you 😀😀😀
