### ISSUE TITLE
arm support for windows

### ISSUE THREAD

**Issue by KazukiSugiyama107** [castlabs/electron-releases#130]
There was a mention of linux and darwin, but since there was no mention of windows, I would like to ask a question.

I would like to know if the Windows and ARM combination is supported.
In case it is not supported, are you planning to add it in future?

**Comment by khwaaj** [comment]
There is no official Widevine CDM available for Windows on ARM, and I am not aware of any timeline for it to be added (Windows on ARM is still considered a niche platform).

If it becomes available at some point in the future we will certainly consider adding support for it to ECS as well. For the time being your only recourse is to rely in the emulation layer Windows on ARM provides.

**Comment by KazukiSugiyama107** [comment]
Thank you for confirmation!

From windows11, x64 emulation function is installed.
I thought this function could also execute x64 code on an arm device, but for an app that used electron-releases, an error occurred during installation.
I'm not sure exactly what caused this problem, but is it possible that electron-releases is involved?

The operation of the application is to start the exe file and download the nsis file placed on S3.
The files are placed correctly on S3, and this error does not occur except for terminals with CPU arm.


The first dialog that appears | Dialog displayed after pressing the cancel button
:--: | :--:
<img src="https://user-images.githubusercontent.com/70558785/168711887-857be9d4-2426-4a06-bfc8-ade94038ce01.png" width="600" /> | <img src="https://user-images.githubusercontent.com/70558785/168711924-acaa7027-c261-4cea-b1f3-7fd2989999f0.png" width="600" />

**Comment by khwaaj** [comment]
The first one is clearly an error from the NSIS Inetc plug-in, so this is likely unrelated to the actual package it tries to install. Unfortunately I don't have access to a Windows on ARM device to do my own testing, and I'm not entirely sure how mature the x64 emulation is (I know some other people here use the ia32 builds for ARM).

Did you try transferring your application as a zip, or similar, to a test device to see if it works without NSIS?

**Comment by KazukiSugiyama107** [comment]
thank you! I tried.
When I launched the app without generating the installer, no error occurred.
From this situation, should we think of it as an NSIS Inetc issue rather than an electron issue?

**Comment by khwaaj** [comment]
Yes, that is my take on it as well. I'm not very familiar with NSIS though, so I can't speculate further on what the actual cause of the issue is.

**Comment by KazukiSugiyama107** [comment]
As we found in additional research, this could be an electronic builder issue rather than an nsis file issue.
The method I tried was to put the exe and nsis files in the same directory and launch the exe file.
The only nsis files I prepared were x64 and x86, but the app installation was completed without any problems.

I will close this once and check with the electron-builder.
thank you very much.

**Comment by imLinguin** [comment]
Hi @khwaaj 
Are there any updates on ARM support? Chromium seems to see some movement with arm64 for Windows https://github.com/chromium/chromium/commit/77efb41adb7b9a99f0827926027ca0f34c381544

**Comment by khwaaj** [comment]
Short update. There is no timeline for this, and support will not come before there is an official release of Chrome available on Windows for ARM. Currently the only way to use the CDM is to rely on the emulation layer.

**Comment by osmestad** [comment]
As Chrome is available for Windows ARM now: https://blog.google/products/chrome/download-google-chrome-windows-pc-arm/ I think this should now be possible? (and desirable :-) )
