### ISSUE TITLE
Custom Uninstall Script causes Javascript Initialization errors 

### ISSUE THREAD

**Issue by jbsupport** [castlabs/electron-releases#135]
Hello,

I am using Castlabs-Electron#v14.2.3-wvvmp to run a Windows App using Shaka Player to play MPEG-DASH content secured using EZDRM. 

I recently added the below "nsis" configuration to my app's package.json with a custom "installer.nsh" to remove files post-uninstall.

![nsisBuild](https://user-images.githubusercontent.com/113500600/190083820-89a24f36-19b8-4ede-a069-15ce28f21691.PNG)

The problem is that the moment this script was added to the package.json, every build threw the following error after the application was installed and run:
![initerror](https://user-images.githubusercontent.com/113500600/190083956-79dc6b11-940a-4ec5-a849-0ccf943c4132.PNG)

The above error continues to occur unless I put the `require("macaddress")` inside the function being called. This repeats for all such modules and global variables.

The following are my BrowserWindow settings:
![browserOptions](https://user-images.githubusercontent.com/113500600/190084124-ae972150-948f-4996-b7f1-e78ce0cf4316.PNG)

I am unable to find a solution that addresses the problem. If I remove the "nsis" configuration, then the application installs and runs without issue on any system.

I would appreciate any input on why this error is occurring only when I add the "nsis" config and any methods on debugging the issue.

If further information is required, please let me know.

**Comment by khwaaj** [comment]
AFAICT this does not look like an ECS related issue, are you seeing the same problem with stock Electron?

My immediate hunch is that this issue is related to `electron-builder`, not ECS or Electron, but I'm not very familiar with the NSIS installers is I don't really have much advice on that front.

**Comment by jbsupport** [comment]
It might just be the builder since stock electron gives me the same problem. Did not think of it that way. Thank you for the pointers. Will let you know if I need further help
