### ISSUE TITLE
Cannot install the package anymore - getting 404 error

### ISSUE THREAD

**Issue by grekpe** [castlabs/electron-releases#138]
Hi,

I can't seem to be able to npm install the package anymore.

I am getting 404 error on postinstall script:
`HTTPError: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v20.0.0/electron-v20.0.0-darwin-x64.zip`

Comparing the URLs below it looks like the artifact URL generated in positnstall is missing the `%2Bwvcus` bit.

`https://github.com/castlabs/electron-releases/releases/download/v20.0.0%2Bwvcus/electron-v20.3.4+wvcus-darwin-x64.zip`
`https://github.com/castlabs/electron-releases/releases/download/v20.0.0%2Bwvcus/electron-v20.3.4-darwin-x64.zip`

Could you please suggest if I am doing something wrong or if it is an issue within the postinstall script?

Kind regards

**Comment by khwaaj** [comment]
Using`v20.0.0+wvcus` seems to be working fine in my setup. What does your `package.json` and command-line look like?

**Comment by grekpe** [comment]
Hi @khwaaj 

Thanks for your quick response.

`package.json` file contents:
```
{
  "name": "playground",
  "version": "1.0.0",
  "description": "",
  "main": "src/main.js",
  "scripts": {
    "start": "electron .",
    "serve": "serve ./src/webapp",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "electron": "https://github.com/castlabs/electron-releases#v20.0.0+wvcus",
    "rx-player": "^3.28.0",
    "serve": "^14.0.1"
  }
}
```

And here's the command line output after running `npm i`:
```
HTTPError: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v20.0.0/electron-v20.0.0-darwin-x64.zip
    at EventEmitter.<anonymous> (/Users/grekpe/projects/playground/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:315:20)
    at module.exports (/Users/grekpe/projects/playground/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/grekpe/projects/playground/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/grekpe/projects/playground/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
npm WARN playground@1.0.0 No description
npm WARN playground@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@20.0.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@20.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/grekpe/.npm/_logs/2022-11-10T13_12_58_437Z-debug.log
```

Please do let me know should you require any further details.

**Comment by khwaaj** [comment]
Ok, `package.json` looks fine. Which version of `npm` are you running, I know there have been some issues with certain older versions.

**Comment by grekpe** [comment]
I was running node v14.16.1. Seems like changing the node version fixes the issue. I've switched to node v16 now and it works as expected. 

Thanks a bunch @khwaaj !
