### ISSUE TITLE
Not able to install 16.2.8 from gitlab runner. Error: rcedit.exe failed with exit code 1. wine: '/root/.wine' is a 32-bit installation

### ISSUE THREAD

**Issue by demchuk-alex** [castlabs/electron-releases#139]
Hey folks I'm not able to install castlabs electron version 16.2.8. Looks like it generates wrong download url, could you please point out how to specify the correct download URL? 

here is error
`> electron@16.2.8 postinstall /builds/all/pix/legacy/pix-app/p3/lumiere/node_modules/electron
> node install.js
HTTPError: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v16.2.8/electron-v16.2.8-linux-x64.zip
    at EventEmitter.<anonymous> (/builds/all/pix/legacy/pix-app/p3/lumiere/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:[31](https://gitlab.pixsystem.net/all/pix/legacy/pix-app/p3/lumiere/-/jobs/843061#L31)4:20)`
    
  and here is `package.json` fragment 
  
`  "electron": "https://github.com/castlabs/electron-releases#v16.2.8+wvcus",`

**Comment by demchuk-alex** [comment]
Thanks @khwaaj changing node version it helped, however now `electron-packager` doesn't work with 16 version of electron

`Error: rcedit.exe failed with exit code 1. wine: '/root/.wine' is a 32-bit installation`

**Comment by khwaaj** [comment]
Looks like you got a 64-bit `rcedit.exe` and are trying to run it with 32-bit Wine? You probably need to update the Wine installation somehow, but this is not something I have a great deal of experience with. I recommend Googling it 🙂

**Comment by demchuk-alex** [comment]
Ok issue solved, for those who are interested:
Lastest versions of castlab electrons 16+ only installed properly with node 16 as mentioned in [here](https://github.com/castlabs/electron-releases/issues/138)

My last question is related to `electron-packager` usage in gitlab runner with `electronuserland/builder:wine` docker image, so fix could be found [here ](https://github.com/electron/forge/issues/1080) in nutshell 

```python
# Removes the original 32-bit wine prefix from the generated image
rm -rf /root/.wine
# Creates a new 64-bit one
winecfg
```
latter will reinitialize wine and successfully package electron app.
Anyway @khwaaj Thanks a lot!
