### ISSUE TITLE
Add support for `armv7l` architecture (Raspberry Pi)

### ISSUE THREAD

**Issue by James-Livesey** [castlabs/electron-releases#146]
When attempting to build [our Electron application](http://github.com/LiveGTech/gShell) for `armv7l` (ARM 32-bit) devices, there is no `armv7l` release of Electron that includes support for Widevine.

Electron apps run perfectly fine on Raspberry Pi devices due to having build support for `armv7l`. Widevine also runs on the `armv7l` architecture and so is [installable on Raspberry Pi](https://pimylifeup.com/raspberry-pi-widevine/).

It would be hugely beneficial if this fork of Electron supported `armv7l` as it would enable Raspberry Pis to run Electron applications that can access a number of DRM streaming platforms.

I understand that this issue has been previously discussed in #23, but I believe that that issue contains now-outdated information and so is due for reconsideration.

---

**This issue blocks https://github.com/LiveGTech/gShell/pull/21.**

**Comment by khwaaj** [comment]
Unfortunately there is still no _official_ Widevine CDM for any Linux version on ARM, which means we can't support it (and it is not available through the Component Updater). The CDM which is available for raspbian, i.e. through the `libwidevinecdm0` APT package, is not official or sanctioned by Google. AFAICT it comes from ChromeOS and using it has potential legal implications.

We actually specifically asked about this again a couple of weeks back, in another context, and there are currently no plans to support this near term. The audience is simply too small to warrant the investment required 🙁

**Comment by James-Livesey** [comment]
Ah okay, thanks for the clarification! Hopefully at some point they can start supporting ARM Linux in an official capacity 🤞

I'll close this issue for now due to it being an issue for Widevine instead of this project itself.
