### ISSUE TITLE
Crash on Windows with version 23 and later

### ISSUE THREAD

**Issue by vitekcerny** [castlabs/electron-releases#147]
Since version 23, even a minimal electron application cannot be run. Tested on Windows x64 on [electron-quick-start](https://github.com/electron/electron-quick-start) with modifications in your documentation. Everything works up to the latest version 22. Since version 23 the application quits immediately. Everything works fine on macOS x64.

**Comment by khwaaj** [comment]
This is fixed in `v24.0.0-alpha.6+wvcus.2` and `v23.1.1+wvcus.2` respectively. Let me know if there are any further issues.

**Comment by vitekcerny** [comment]
Thank you for the quick response. I can confirm that the binaries are working again on Windows, so we can close this issue now. Thanks again :)
