### ISSUE TITLE
Widevine for linux-arm64

### ISSUE THREAD

**Issue by f1multiviewer** [castlabs/electron-releases#150]
I'm wondering if #114 is still the latest status on Linux ARM64 builds since there seems to be some new developments:

http://archive.raspberrypi.org/debian/pool/main/w/widevine/
https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/248

Does this mean that, in the near future, castLabs would also be able to offer linux-arm64 builds?

**Comment by khwaaj** [comment]
Unfortunately these are not official CDMs for use outside of ChromeOS, and they are not available through the Component Updater, so it is nothing we can support. Google may turn a blind eye to them being used in this context, but would likely react on more widespread use, especially in commercial contexts.

To my knowledge there is no timeline for officially supporting non-`x86_64` CDMs on Linux at this time.

**Comment by f1multiviewer** [comment]
Right, that makes sense, thanks for the quick answer! 💚
