### ISSUE TITLE
Code signing + VMP signing on Windows (using Electron Forge)

### ISSUE THREAD

**Issue by f1multiviewer** [castlabs/electron-releases#156]
So I've been trying to get Electron Forge to sign an Electron ECS build, while keeping the EVS signature intact. So far, it doesn't seem to work.

In which order should the signing happen on Windows? Sign the binary first, then EVS? Or the other way around?

**Comment by khwaaj** [comment]
On Windows you need to VMP-sign after you code-sign, or the signature will break. This is because code-signing on Windows modifies the executable, and _ANY_ change to the executable after VMP signing on Windows will break the generated signature.

**Comment by f1multiviewer** [comment]
Oh, and the VMP signature doesn't change the binary? So it keeps the code-signing intact? If so, feel free to close it :)

**Comment by khwaaj** [comment]
No, the VMP signature is stored in a separate file so it does not affect code-signing on Windows. If you support macOS too though, [signing needs to be done the other way around though](https://github.com/castlabs/electron-releases/wiki/EVS#signing-an-ecs-application-package). Just something to be aware of.

Closing as requested.

**Comment by f1multiviewer** [comment]
Yeah macOS signing is already working as expected, but I noticed on Windows the same order didn't work, so this clears that up, thank you!

**Comment by Mgrdich** [comment]
but on electron forge signing is done on the installer level , in that way there is no way you can sign the DRM after the Signing , i don't honestly know how they are signing there, but all the electron windows installer packages works with signing on the installer level.
