### ISSUE TITLE
App on windows works as expected but on linux it crashes

### ISSUE THREAD

**Issue by KonstantinSavik** [castlabs/electron-releases#168]
Hi!
When I tried to run app on Ubuntu OS it crashes with error:

``` 
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94713)
    at WebContents.send (node:electron/js2c/browser_init:2:80073)
    ....
```
Actually, window is opened, but there are no any content

On Windows OS it forks fine.

Did I miss something in cofiguration?

**Comment by khwaaj** [comment]
I've not seen this issue before, and it does not appear to be ECS specific. Googling the message gets some hits with suggestions with everything from clearing the cache/preferences to more advanced topics (like incompatibilities in the used `glibc` build).

Are you seeing this with multiple versions of ECS, or just one? And did you try clearing the data in `~/.config/<your-app>`?

**Comment by KonstantinSavik** [comment]
Ok, thanks, you are right
Something on 25 version everything is work, but on 26+ no
