### ISSUE TITLE
NixOS Widevine Not Recognized

### ISSUE THREAD

**Issue by zoe2276** [castlabs/electron-releases#174]
**Platform:** NixOS 23.0.1 (development)
**Version:** ECSv26.6.0 (also tested with 27.1.0)

Hello,

I'm building an application in Electron meant to interact with content that requires Widevine's CDM. I'm aware that Linux is a funky child when it comes to CDM, and that ECS is not immune to this, although I am not sure that this is even the issue.

Per some other research I've done trying to get Electron to even start within my NixOS environment (development only, I haven't even built the application yet), `npm` can't be used to install electron and, in fact, causes an `ENOENT` error whenever you simply run `npm i` followed by `electron .`. The fix for this is to delete `/node_modules/bin/electron` (i've started renaming to .old so I can resume quickly from my Windows dev environment) and instead run `nix-shell -p electron` to temporarily expose the electron packages to PATH and allow the application to run.

This process works great... until I came across needing Widevine support. I've tried using electron's documented "solution" of running the app with the command-line flags to no avail, as well as editing the ELECTRON_MIRROR and ELECTRON_CUSTOM_URL environment variables to point to the above releases, but the end-all seems to be electron's issue with running within NixOS in general.

I'm at a bit of a loss here, and I'm not sure where else to start looking. When trying to use the documented `components.whenReady()` event, I'm greeted with an error that `components` is `undefined` (the error technically says that it can't read the property `whenReady()` of `undefined`).

I'm at the point where I'm considering distro-hopping to solve this issue. Please let me know what, if anything, I can provide to help get to the bottom of this, whatever that looks like.

Thanks in advance!

**Comment by khwaaj** [comment]
It is hard to get any feel for the problem from this information, and in general we don't really have the resources in this project to test the various Linux distros available. We have had reports of issues in some of them before, but this seems like something else - at least on the surface.

> The fix for this is to delete /node_modules/bin/electron (i've started renaming to .old so I can resume quickly from my Windows dev environment) and instead run nix-shell -p electron to temporarily expose the electron packages to PATH and allow the application to run.

Are you sharing the same working copy on both Windows and Linux? If so, I'd say this is quirky and likely to cause some headaches. If you are doing this, I'd start by trying to use a clean Linux-only working copy on NixOS.

> When trying to use the documented components.whenReady() event, I'm greeted with an error that components is undefined (the error technically says that it can't read the property whenReady() of undefined).

This seems to hint at one of two things. Either you are not actually using ECS at all (this can happen, check the `node_modules/electron/dist/version` file for the version used) or you are not [importing the `components` API](https://github.com/castlabs/electron-releases#using).

**Comment by zoe2276** [comment]
This is starting to feel more and more like a perfect storm. I've spent all of today exploring Nix's options for allowing this to work (overlays, package overrides, yarn2nix/nixfromnpm) that are falling apart due most likely to my own lack of familiarity with the operating system to that level. 

> Are you sharing the same working copy on both Windows and Linux? If so, I'd say this is quirky and likely to cause some headaches.

I am; that's why I've been renaming `/bin/electron` to `/bin/electron.old` and then simply renaming the package before updating my NPM packages back on my Windows machine, and the inverse on my NixOS machine. Regarding the pure Linux dev environment, that's essentially where I'm at right now. I'm out of town for the American holidays and only have my laptop, which is my NixOS environment. I haven't ran back to Windows to even test ECS over there as I simply haven't had access to it.

> or you are not [importing the components API](https://github.com/castlabs/electron-releases#using).

I am; it shows `components` as being of type `Electron.Components` in the VSCode tooltip, and `node_modules/electron/dist/version` has `26.6.0+wvcus` within it. In fact, I commented most of my `main.js` as a test and replaced my code with that provided in the #Using section, with no result. For fun, here's the current state:

```const { app, components, BrowserWindow} = require('electron');

const createWindow = () => {
    const win = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            nodeIntegration: true,
            plugins: true
        }
    })
    win.loadURL("http://localhost:3000")
    // widevine testing url:
    // win.loadURL("https://shaka-player-demo.appspot.com/")
    win.webContents.openDevTools()
}

// app.commandLine.appendSwitch('widevine-cdm-path', '../cdm/linux/')
// app.commandLine.appendSwitch('widevine-cdm-path', '/nix/store/mcanzi7lsnz8gk4r50sdkqdy5k85niih-google-chrome-119.0.6045.123/share/google/chrome/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so')
// app.commandLine.appendSwitch('widevine-cdm-version', '4.10.2710.0')

app.whenReady().then(async () => {
  await components.whenReady();
  console.log('components ready:', components.status());
  createWindow();
});
```

As stated previous I am still looking at exploring Nix's inbuilt options to deal with this situation (overlays seem the most promising but I'm running into my own errors on that front) but just in case someone knew something that I didn't, I wanted to fire an issue over here. 

All of this being said I'm fairly certain it has more to do with NixOS than ECS. Let me know if you have any other ideas before closing this one out, but my expectations are dwindling quickly. If I come up with a solution for this, I'll throw it up here under this issue just in case someone has this issue in the future and try to pay it forward!

**Comment by zoe2276** [comment]
Gave up on NixOS. Closing this due to current irrelevance.

If anyone comes across this, check out `nix-ld`. I wasn't willing to sacrifice the 'purity' of NixOS but that seemed to be as close as I was going to get.

Thanks for your help!
