### ISSUE TITLE
Cannot build both mac intel and mac arm on apple m1 using castlab releases >26 when using binary main code 

### ISSUE THREAD

**Issue by radislav** [castlabs/electron-releases#183]
Using <27 I can build both Arm and Intel versions on M1 platform, but starting v27 I still can build but it's impossible to run Intel version of this build because I see error like "Built version used another node engine (incompatible with runner version)"
With original Electron releases, I don't see such problems

**Comment by khwaaj** [comment]
Thanks for the report. I have an idea about this, but first: What version of node.js are you running on the M1 machine in question?

**Comment by radislav** [comment]
node: 18.18

**Comment by khwaaj** [comment]
Ok, It looks like the build Mac was stuck on nodejs 16, so that could explain the problem. I made some adjustments so `v31.0.0-alpha.4+wvcus` will be the first build to deploy with these changes (it is building now).

**Comment by radislav** [comment]
Thanks a lot
Seems I should've created the issue earlier :)
