### ISSUE TITLE
Issues with release build and VMP signing

### ISSUE THREAD

**Issue by therampant** [castlabs/electron-releases#21]
After creating an electron build using 'nmp run release' and then VMP signing that .exe following the instructions here: https://github.com/castlabs/electron-releases#verified-media-path-vmp I can open the .exe but the videos fail to play. With the console open we can what look to be various code signing issues.

At this point we just don't know enough about the system to begin debugging. Is there any way to tell that the VMP signing was successful? Is there a way that we can troubleshoot our widevine certificate?

To be clear, our use case is that a user will download content with an internet connection, and then later play that content without an internet connection.

![unnamed](https://user-images.githubusercontent.com/897957/45775409-4e5f3e80-bc15-11e8-9799-5efae5e3503f.png)

Thanks,
Ben

**Comment by khwaaj** [comment]
I don't remember why this was never followed up, but since it appears to be using PRESTOplay I'd assume it was handled through regular castLabs support channels.

Anyway, since this issue is now _very_ old, I'll go ahead and close it. Feel free to resubmit if there are further problems.
