### ISSUE TITLE
ARM Linux support

### ISSUE THREAD

**Issue by robertoviola** [castlabs/electron-releases#23]
Hi,
I would like to develop a Widevine enabled player for Linux based OS and ARM architecture. I would like to know if such combination of operating system and architecture is supported by electron.
In case it is not supported, are you planning to add it in future?
Best regards,
Roberto

**Comment by khwaaj** [comment]
Hi @robertoviola,

Electron itself does have support for linux+arm/arm7l/arm64 but I do not have knowledge of **_official_** Widevine CDMs that do, so we are not currently supporting this. I'll bring the request up when we next sync with our Widevine contacts, maybe I'll be able to provide a more complete answer then.

Best,
Emil

**Comment by khwaaj** [comment]
Hi,

Unfortunately this is not something Widevine will pursue currently since the use-case is simply too small to warrant maintaining a separate CDM for it. This means we can't support this for the time being.

Best,
Emil

**Comment by mihaiav** [comment]
Is there any update on this? It seems Google has Wildevine support on ARM through its ChromeOS. There seem to be some hacks `[0]` to "make it work" so it's a bit unfortunate that there is no official solution.
 We are working on a  Linux/ARM powered set-top box (STB).
`[0]` https://lemariva.com/blog/2020/06/raspberry-pi-amazon-prime-netflix-and-drm-solution

**Comment by khwaaj** [comment]
Unfortunately there have been no changes on this topic. An ARM CDM has been available through ChromeOS for quite a while, but it is not an officially supported browser CDM and thus not something we can endorse as a solution for ECS, both for legal and practical reasons. For example it is unpractical to handle system-id revocations and CDM updates using a non-official path, which makes any such solution very fragile.

On the bright side ARM is growing as a desktop platform, with both Windows and macOS embracing it these days, so let's hope the increased interest may eventually lead to something here.

If you are building hardware STB device there are potential Widevine L1 options that you could look into, depending on the chipset you are using. It would be more involved than using something finished like the browser CDM, but if you are interested [castLabs](https://castlabs.com/contact/) could help you look into options.

**Comment by khwaaj** [comment]
@andirsun, we are well aware of this possibility, but since it is not officially provided by Widevine we can't support it. For two reasons really:
1. This project was created in collaboration with Google Widevine, and they do not condone CDMs from non-official sources.
2. The CDM contains video decoders, and thus requires MPEG-LA licensing. As long as the CDM is hosted by Google and dynamically installed from their serves, the license they have is enough. Hosting and/or bundling the CDM outside of Google could incur license requirements, and thus have legal consequences.

**Comment by khwaaj** [comment]
That said, there is a way to officially support Widevine on Linux devices (albeit typically not desktop systems). It would mean custom engineering and the use of something called the CE-CDM (L1 or L3). As a Widevine 3PL partner castLabs also do these kinds of projects for companies building devices with this requirement.
