### ISSUE TITLE
Installation with Yarn does not work since v3.0.0

### ISSUE THREAD

**Issue by Gontran-Molotov** [castlabs/electron-releases#25]
Since version 3.0.0, electron-releases can no longer be installed using Yarn. 

An example with v3.0.2: the URL used by Yarn to download the dependency on MacOs is `https://github.com/castlabs/electron-releases/releases/download/vv3.0.2-wvvmp/electron-vv3.0.2-wvvmp-darwin-x64.zip`. Note the double `v` in the URL before the version number.

Is it due to the value of the `version` key in `package.json`? In version 1.8.8, the value is `1.8.8-vmp1010`. In version 3.0.0-wvvmp-beta.9, the value is `v3.0.0-wvvmp-beta.9`. The value now starts with a `v`.

**Comment by khwaaj** [comment]
Ah, good catch! The discrepancy in `package.json` is very likely the culprit here, I'll see about getting it fixed.  We missed this in our tests since `npm` seems to be more tolerant in this case, ignoring the extra `v`.

**Comment by khwaaj** [comment]
I re-tagged v3.0.4-wvvmp with a fixed version of `package.json` so it should work now. Let me know if it doesn't.

**Comment by Gontran-Molotov** [comment]
Works like a charm. Thank you!

**Comment by khwaaj** [comment]
Great, I'll close this then.
