### ISSUE TITLE
Symbols

### ISSUE THREAD

**Issue by michaelenger** [castlabs/electron-releases#26]
We're using [crashReporter](https://electronjs.org/docs/api/crash-reporter) to send crashes to an external server and to be able to see where the crashes occurred we need to upload the symbols to our crash server. Can we use the symbols provided in the regular Electron releases, or can we get them from you?

**Comment by khwaaj** [comment]
No, the symbols are build-specific so using the stock electron ones won't work.

Which release are you using? For the 1.8 series we can't publish any symbols but I'll see about starting to do it for the later series, i.e. from 3.0.8 (and 4.0.0, which is in the pipeline).

**Comment by alexanderturinske** [comment]
Bumping this issue. 

We also have crashReporter set up and I have upload many files by now trying to get symbols working. I have been able to get the Mac symbols mostly working, but the Win side is still pretty bad.

**Comment by khwaaj** [comment]
FYI, I just published [electron 3.0.8-wvvmp](
https://github.com/castlabs/electron-releases/releases/tag/v3.0.8-wvvmp) which includes the breakpad symbols.

**Comment by khwaaj** [comment]
Closing this since symbols are now included in all releases since 3.0.8. Feel free reopen if anyone still have some problems/reservations around this.
