### ISSUE TITLE
Widevine events don't exists

### ISSUE THREAD

**Issue by TheRolfFR** [castlabs/electron-releases#29]
Hello,

I've been trying to develop with widevine since 2 days but I couldn't find what's wrong with me.
I havd replaced the stock electron with yours but when I start none of the widevine events fired. When I printed the app variable from my require('electron') I figured out that the events doesn't exists.

`_events:
   { login: [Function],
     'certificate-error': [Function],
     'select-client-certificate': [Function],
     quit: [Function],
     'web-contents-created': [Function],
     'session-created': [Function],
     'will-quit': [Function],
     ready: [ [Object], [Object], [Function] ],
     'window-all-closed': [Function] }`

I am using the latest version of your electron. May I missed something important to have widevine working ? Do I have to build it in order to test it ? Thanks

**Comment by khwaaj** [comment]
Hi!

Sorry for the delay in responding. Is the still an issue for you? In case it is I need some more information to be able to look into this as it is something I've not seen or heard about anyone having trouble with before. Also, I'm not entirely sure I understand the exact nature of the problem from the description above, I would not expect the Widevine related events to fire until you actually try to play some Widevine protected content back. Some questions that may help if you can answer:

1. Which version of electron were you using before trying a castLabs release?
2. Which castLabs electron release are you using?
3. Which platform are you running on?
4. How are you testing Widevine playback, and how/when are you expecting the events to fire?
5. Does the same type of approach work as expected in Chrome, as opposed to electron?
6. Does Widevine playback work when loading e.g. the [shaka-player demo page](http://shaka-player-demo.appspot.com) in electron and selecting Widevine protected content?

**Comment by TheRolfFR** [comment]
Thanks,

I found the problem which was veeeeery stupid. In fact, I was not launching the CatLabs version of electron. I figured out I had to launch the node modules version so I did a script in my package.json :

```json
"scripts": {
    "start": "node_modules\\electron\\dist\\electron.exe ."
  }
```

I was just a dumb ass xD .

Thanks for your help. I close the issue.
