### ISSUE TITLE
Linux Snap Packing

### ISSUE THREAD

**Issue by oscartbeaumont** [castlabs/electron-releases#37]
Hello,
I am the developer on a project called [Electron Player](https://github.com/oscartbeaumont/ElectronPlayer) and I recently moved to use your package for the Linux version of the app (couldn't get Mac working but that's another problem). I package the app using [electron-builder](https://github.com/electron-userland/electron-builder) and for one of my publishing platforms, I am using [snapcraft](https://snapcraft.io/) as it is popular on Linux. I had to pull the update changing to your package as I noticed it would not launch and after some debugging, I am pretty sure the cause is your package. It works outside of the snap environment but inside it does not. Snapcraft sandboxes applications running in it and looking at the logs it is blocking a sysctl call. I assume whatever this call is it is being blocked and is causing everything after to fail and hence the app to never launch. Is there a possible fix for this? My codebase is linked above and the error it is showing in the snap developer logs when starting the application is below. I also need to try and fix this as fast as possible as I moved to your package as a fix to the broken Netflix player, one of the main functions of the application.
```
= AppArmor =
Time: Jun 18 19:22:14
Log: apparmor="DENIED" operation="open" profile="snap.electronplayer.electronplayer" name="/proc/11538/setgroups" pid=11538 comm="electronplayer" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
File: /proc/11538/setgroups (write)
Suggestion:
* adjust program to not access '@{PROC}/@{pid}/setgroups'
```
All your help will be appreciated

**Comment by khwaaj** [comment]
Hi,

I took a quick look and this appears to be a feature of the linux sandboxing that Chromium uses. I don't have time for a deeper delve into this right now as I'm on PTO for another week but I would suggest trying to pass the [`--no-sandbox`](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#--no-sandbox) option when you start Electron and see if it makes a difference.

**Comment by oscartbeaumont** [comment]
Thanks that helped fix the problem. There was a bug fix in the latest alpha version of electron-builder which disables the sandbox for the snap version of the application.
