### ISSUE TITLE
Is controlling when the CDM upgrades possible?

### ISSUE THREAD

**Issue by simongregory** [castlabs/electron-releases#39]
For rights reasons we geo ip block out of country downloads, this includes license issue. However we support download in country and watch anywhere (with persistent licenses) but users are getting tripped up by CDM upgrades requiring license reissue. In one case a charity worker arrived abroad with enough content to cover the 3 months they were away to find they couldn't watch it.

Obviously there's going to be scenarios where the CDM needs upgrading regardless. However I don't know what the policy actually is, so might there be some room for being able to control when an upgrade happens?

**Comment by khwaaj** [comment]
Interesting, this is a case we have clearly overlooked where internet access is available but the ability to request licenses is not. I will see about the possibility of adding something to handle cases like this.

In the meantime there is a bit of a hackish solution you might employ that could allow you to work around this, if you are using recent enough release (3.1.9, 4.2.0 or 5.0.1, or later in respective series). The idea is that you could use [`verifyWidevineCdm`](https://github.com/castlabs/electron-releases#appverifywidevinecdmoptions) to dynamically override the Widevine configuration if you are in *offline* mode, more specifically to override the `versionPattern` to only look for the version that is already installed. The `versionPattern` option is currently undocumented but it is a RegEx pattern that decides which versions to consider when performing a CDM update, e.g. `"^4\\.10\\..+$"` for all CDMs in the 4.10 release series (it can even be used to force a downgrade). By saving the currently installed version and generating a pattern based on that when in *offline* mode, you could make sure an update is not installed. There is an edge case here too however: If an update is already pending (downloaded during the users last session and awaiting restart before being applied) just changing the `versionPattern` won't be enough to stop it. To avoid this you can override the `updateDir` option, defaulting to `"{{baseDir}}/WidevineCDM.pending"` but also currently undocumented, pointing it to a non-existant directory. Example call for forcing CDM 4.10.1196.0 in *offline* mode, ignoring any pending update:

```
app.verifyWidevineCdm({
  versionPattern: "^4\\.10\\.1196\\.0$",
  updateDir: "{{baseDir}}/WidevineCDM.pending-ignore"
});
```

It is important the `versionPattern` really represents the currently installed version, e.g. as provided in the `widevine-ready` event, or this would instead force an upgrade/downgrade to commence.

**Comment by khwaaj** [comment]
I finally got around to doing something about this. The latest release, [electron 6.0.2-wvvmp](https://github.com/castlabs/electron-releases/releases/tag/v6.0.2-wvvmp) contains [new options](https://github.com/castlabs/electron-releases/tree/v6.0.2-wvvmp#widevine-specific-apis) to control the update behaviour. This will roll out to the other release series too as new releases are made available.

Check it out and let me know what you think!

**Comment by simongregory** [comment]
Apologies for the lack of a response on this, I've been both away and addressing other work. Hopefully I'm getting the time to investigate properly shortly, but your changes look good, so thanks in the meantime.

**Comment by simongregory** [comment]
All implemented our side. Thanks again @khwaaj
