### ISSUE TITLE
Electron 6.1.3 - missing SHASUM256.txt file

### ISSUE THREAD

**Issue by jeremco** [castlabs/electron-releases#44]
Hi,

Using npm, electron 6.1.3 cannot be installed, because SHASUM256.txt is missing: 

Here is the log : 
node install.js

Downloading tmp-15326-0-SHASUMS256.txt-6.1.3-wvvmp
Error: GET https://github.com/castlabs/electron-releases/releases/download/v6.1.3-wvvmp/SHASUMS256.txt returned 404

/Users/jeremie/Documents/01-Taf/01-Dev/PlayerJavascript/gitlab/LVO/sources/node_modules/electron/install.js:54
  throw err
  ^

Error: Failed to find Electron v6.1.3-wvvmp for darwin-x64 at https://github.com/castlabs/electron-releases/releases/download/v6.1.3-wvvmp/electron-v6.1.3-wvvmp-darwin-x64.zip

Jérémie

**Comment by khwaaj** [comment]
Hi Jérémie,

I added the missing file to the 6.1.3-release, thanks for the heads-up!

**Comment by jeremco** [comment]
Hi Emil,

It's ok for me

Thanks

**Comment by khwaaj** [comment]
Nice, thanks for the update!
