### ISSUE TITLE
On close error

### ISSUE THREAD

**Issue by IhorVimmi** [castlabs/electron-releases#49]
hi! I need help) 
When I close my app I've got next error http://joxi.ru/1A55aqduDOzZOA
Tell me please where is it may happend

**Comment by khwaaj** [comment]
I'm guessing you may be handling an asynchronous event after the referenced windows has been closed, and not catching the exception raised. Maybe something akin to [this](https://stackoverflow.com/questions/55395748/object-has-been-destroyed-when-sending-through-ipc).

For the future please try to keep issues/questions reported in this repository related to Widevine and/or media playback. For more general questions such as this you are better off asking in the stock [Electron community forums](https://electronjs.org/community).

**Comment by IhorVimmi** [comment]
@khwaaj sure, thank you)
