### ISSUE TITLE
Building for Mac with electron-builder

### ISSUE THREAD

**Issue by nickdima** [castlabs/electron-releases#51]
We are building our app using `electron-builder`, signing it for distribution outside the MAS and [notarizing it](https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/).
As per the instructions in the readme we are VMP-signing before code-signing. We do this by using the [afterPack](https://www.electron.build/configuration/configuration.html#afterpack) hook which just calls your python script from a JS function. This hook should run before code-signing and by looking at electron-builder's output the order seems to be fine.
The problem is that when running the app for some reason Widevine doesn't seem to work.
Just by simply disabling the code-signing [like this](https://www.electron.build/code-signing.html#how-to-disable-code-signing-during-the-build-process-on-macos) we get a working build which is able to use Widevine.
Anyone knows what we're missing here?

**Comment by khwaaj** [comment]
What kind of error are you seeing? Could it be the same error as in #38?

**Comment by nickdima** [comment]
That was it! Disabling library validation like this:
```
<key>com.apple.security.cs.disable-library-validation</key>
<true/>
```
in the entitlements file solved the problem.
Maybe we should add this to the readme? I could send a PR tomorrow.

**Comment by khwaaj** [comment]
Indeed something for the README. I was actually meaning to add it after #38 but it got lost somewhere along the way. A PR would be nice, thanks!

**Comment by toschlog** [comment]
Yes, someone should add this to the README.  We spent a day banging our heads on this issue until I found this post :)
