### ISSUE TITLE
CDM not loading on Windows 10 networked appdata folders

### ISSUE THREAD

**Issue by simongregory** [castlabs/electron-releases#52]
We've received the following from a user who is trying to upgrade a few machines to use the latest version of our app. It's based on ~~v7.1.9-wvvmp~~ v7.1.1-wvvmp  and trying to load ~~v4.10.1582.2~~ v4.10.1582.1 of the CDM. The user is running Windows 10 1809, and their logs don't show any`widevine-` events.

> I believe the app has a problem because when running as a user without appdata re-directed, all the appdata is stored in c:\users\user\appdata eg \local\BBCiPlayerDownloads \roaming\BBCiPlayerDownloads
> when the user (even an admin user) has their home folder re-directed, they have split appdata
> so c:\users\user\appdata\local\BBCiPlayerDownloads and \\network_path\user\appdata\BBCiPlayerDownloads app (for roaming)
> It looks to me maybe that the app doesn't like this split, as the same computer will run BBCiPlayerDownloads app on a user logged in without folder redirection.

This looks as though it's in the same area as #50 with the CDM being affected by filesystem virtualisation/redirection. Does this sound reasonable? The difference being that `widevine-ready` doesn't fire, and versions of Windows pre-dates the version expected to cause problems.

**Comment by khwaaj** [comment]
Yes, it appears to be a similar issue (albeit not exactly the same). The core issue causing the failure is likely the same thing though, that the CDM does not allow itself to execute from a virtualized or redirected filesystem location. I'm not sure why you are not seeing any Widevine events though as they are actually sent in the case described in #50.

It is unclear if there is a good alternative to install the CDM on Windows, where the app would have access to write/execute but that is never virtualized/redirected in any way. If the whole home folder is actually redirected the solution suggested in #50 won't work as it still installs the CDM to the user folder. Maybe the global ProgramData folder is an option, but I'm not sure if that would work in a Windows Store app.

Do you have access to an environment exhibiting this problem where you could try to change `baseDir` as described in #50 to see if you can use another directory, e.g. `C:\ProgramData\Widevine`, and make it work?

**Comment by simongregory** [comment]
I don't have access to an environment to replicate the issue which is one of the reasons I wanted to check here to see if I was on the right path before looking into setting one up - or providing the user with a custom build to test with.

The lack of events I originally put down to a local transport error but have been assured there aren't any restrictions. I can see in the log the previous version of the CDM is installed so it has worked in the past.

It would be interesting to know if Google solved this issue for Chrome, obviously they can bundle the CDM binary without the licensing restrictions, but if they're still updating the CDM independently then they need somewhere 'real' to write to.

Will update once I know more, thanks for the help.

**Comment by khwaaj** [comment]
This distinction between Electron versions is interesting to me since both the comments in #50 and here seems to indicate this worked in earlier versions of Electron, even though they are actually using the same version of the CDM. I think I need to set up some kind of test to see if I can reproduce the difference in behaviour.

Yeah, I've been meaning to ask my contacts about this, but for various reasons I've not gotten around to it yet. I'll see if I can get some input from going forward.

**Comment by simongregory** [comment]
I've had a response from our user who was having trouble with the installs. They've got a test build working by finding a path on `C:\` and setting it via `--widevine-base-dir`. `C:\ProgramData\Widevine` didn't work for non-admin users, so they had to setup a directory to sandbox the cdm for non-admin users as their machines are locked down.

Apologies for being inaccurate but previously they were using `v7.1.1-wvvmp` with `4.10.1582.1`, and are now using `v7.1.9-wvvmp` with `v4.10.1582.2`.

My plan is to simulate the 2 problems with restricted and aliased folders and see what errors I get, I'm hoping off the back of this I'll have some more concrete info on the errors raised at which point I can advise users there's a problem and get some idea of volumes via stats. Will let you know how that goes.

**Comment by khwaaj** [comment]
With the advent of the Component Updater Service based releases we have even less control over the installation than before, which limits out ability to do much to work around issues like this. At the end of the day this is caused by the restrictions imposed by the Chromium sandbox, and thus any attempts to fix the root cause has security implications.

Since this is not an old issue I'll close it due to inactivity.
