### ISSUE TITLE
Release v9.2.1 issue

### ISSUE THREAD

**Issue by holmberd** [castlabs/electron-releases#60]
The v9.2.1 release doesn't seem to be correct.

The Electron v.9.2.1 release includes a fix for disabling CORS for extensions. I've been running the Electron release and tests for this have passed. Installing the castlabs release seems to not contain this fix causing tests to fail.

![image](https://user-images.githubusercontent.com/13058304/90829796-4d4d5500-e2f5-11ea-975e-9512c0810cda.png)

Ref:
- https://github.com/castlabs/electron-releases/releases/tag/v9.2.1-wvvmp
- https://github.com/electron/electron/releases/tag/v9.2.1

**Comment by khwaaj** [comment]
Strange, I just checked that there were no problems during the merge of v9.2.1, and there were not. Looking at the commits the CORS fix, electron/electron#24915, is indeed included in the build of v9.2.1-wvvmp, so something else is going on here. A few of questions:

* Is this something you are seeing on more than one platform?
* Can you reproduce this in v10.0.0-wvvmp-beta.19, or later, which has the parent fix electron/electron#24483?
* Do you have a reliable way to reproduce the problem that you can share?

**Comment by holmberd** [comment]
This seems to have been resolved.

It was odd since it occurred both when building locally and with our CI remotely. Verified module hash in package-lock, npm cache was forcefully cleaned, whole directory was nuked and cloned, same issue. Some ghost upstream, very strange.
