### ISSUE TITLE
Castlabs electron not working as expected

### ISSUE THREAD

**Issue by Odisseuss** [castlabs/electron-releases#61]
Hello,

I am currently working on a project that uses the Spotify SDK and after hours of searching I found an article which mentioned using the Castlabs electron release for getting widevine support in electron.

After installing the latest castlabs release the code which worked with stock electron is not working anymore. In my code, when a user clicks a button in the main window, i use electron.remote to open another BrowserWindow in the render process. With stock electron this all worked fine, but now i am getting an error that says 'cannot read property BrowserWindow of undefined' which is triggered because of this particular line: 'const BroserWindow = remote.BrowserWindow;'

Does anyone know why this happens? Maybe I forgot something...

Thanks

**Comment by khwaaj** [comment]
You didn't specify the versions you were using, but could [this](https://www.electronjs.org/docs/breaking-changes#default-changed-enableremotemodule-defaults-to-false) perhaps be the issue?

**Comment by Odisseuss** [comment]
Thanks for the response. I was using stock electron 10.0.0. After i switched to the castlabs release i used 10.0.0 beta 21. But your advice fixed the issue! I did not think of it though, as this was introduced in electron 10.0 and both releases i used were at least 10.0. But anyway, thanks so much for your help!
