### ISSUE TITLE
Widewine Installation Fails

### ISSUE THREAD

**Issue by vipul-vinsol** [castlabs/electron-releases#64]
When I try to use a `preload` script on `BrowserWindow`, restarting the app results in an error.  
Error:-  
`Failed to install Widewine`   
  
It also fails when I use `nodeIntegration: true`  
  
Are these knows constraints ??

**Comment by khwaaj** [comment]
I'm not sure exactly what is happening in your case, at least not without more information, but are you handling the [Widevine specific events](https://github.com/castlabs/electron-releases#widevine-specific-events) and waiting for `widevine-ready` before opening your BrowserWindow?

Also, is there any more information in the error than what is above? There should be an error object provided with some more details that should help to understand what went wrong.

**Comment by vipul-vinsol** [comment]
```
'use strict';
const { app, BrowserWindow } = require('electron');
const createWindow = () => {
  const mainWin = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: false,
      plugins: true
    }
  });
  mainWin.loadFile('player.html');
}
app.on('widevine-ready', createWindow);
```

Here is the code I am using and this works fine. I am also using PrestOplay v6.x. If I turn the `nodeIntegration: true`, I get

```
Uncaught Error: Cannot find module './cl.core.min.js'
Require stack:
- /home/vipul/projects/uLesson-desktop-poa/player.html
   at Module._resolveFilename (internal/modules/cjs/loader.js:961)
   at Function.i._resolveFilename (electron/js2c/renderer_init.js:42)
   at Module._load (internal/modules/cjs/loader.js:844)
   at Function.Module._load (electron/js2c/asar.js:769)
   at Module.require (internal/modules/cjs/loader.js:1023)
   at require (internal/modules/cjs/helpers.js:77)
   at cl.mse.min.js:245
   at cl.mse.min.js:248
```

Electron version `"electron": "git+https://github.com/castlabs/electron-releases.git#v10.0.0-wvvmp"`

I tried the preload script again and it seems to be working now.  
Also, just a side question, is there a way for me to use local mpd file paths with v6.x prestoplay. It works for online, but gives me an invalid url schema error when I try an offline path

**Comment by vipul-vinsol** [comment]
```
'use strict';
const { app, BrowserWindow } = require('electron');
const createWindow = () => {
  const mainWin = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: false,
      plugins: true
    }
  });
  mainWin.loadFile('player.html');
}
app.on('widevine-ready', createWindow);
```

Here is the code I am using and this works fine. I am also using PrestOplay v6.x. If I turn the `nodeIntegration: true`, I get

```
Uncaught Error: Cannot find module './cl.core.min.js'
Require stack:
- /home/vipul/projects/uLesson-desktop-poa/player.html
   at Module._resolveFilename (internal/modules/cjs/loader.js:961)
   at Function.i._resolveFilename (electron/js2c/renderer_init.js:42)
   at Module._load (internal/modules/cjs/loader.js:844)
   at Function.Module._load (electron/js2c/asar.js:769)
   at Module.require (internal/modules/cjs/loader.js:1023)
   at require (internal/modules/cjs/helpers.js:77)
   at cl.mse.min.js:245
   at cl.mse.min.js:248
```

Electron version `"electron": "git+https://github.com/castlabs/electron-releases.git#v10.0.0-wvvmp"`

I tried the preload script again and it seems to be working now.  
Also, just a side question, is there a way for me to use local mpd file paths with v6.x prestoplay. It works for online, but gives me an invalid url schema error when I try an offline path

**Comment by khwaaj** [comment]
It looks like some part of PRESTOplay is missing, or at least inaccessible, but this is really not my area, so for PRESTOplay I think I'll need to refer you to castLabs support.

PRESTOplay should support offline playback just fine though, but again, you are probably better off asking through castLabs support than here. I know [DOWNstream for Electron](https://castlabs.com/resources/downstream/) has been used for this purpose, so maybe you can find some hints there or in the [GitHub repo](https://github.com/castlabs/downstream_electron).

**Comment by vipul-vinsol** [comment]
Thank you for your help. I will try to reach the support team.  
  
Have a great day, cheers :)
