### ISSUE TITLE
Error while packaging with electron-builder

### ISSUE THREAD

**Issue by olirehacek** [castlabs/electron-releases#65]
Hi,

I am running into a issue while packaging the app for distribution using electron-builder. (macOS)
While the **electron-releases#v10.0.0-wvvmp-beta.25** is specified in my Dependecies in package.json:

`"devDependencies": {
    "electron": "https://github.com/castlabs/electron-releases#v10.0.0-wvvmp-beta.25",
    "electron-builder": "^22.8.0"
  }`

yarn or npm is still crashing on following:

`" ⨯ cannot resolve https://github.com/electron/electron/releases/download/v10.0.0-wvvmp-beta.25/electron-v10.0.0-wvvmp-beta.25-darwin-x64.zip: status code 404"`

It is obviously trying to connect to the official electron GitHub repo and download the fork from there.
Any idea how to fix it ?

Best regards,
Ondrej

**Comment by simongregory** [comment]
If you read the docs for electron-builder you should find there's a way to configure it with mirror options. It'll means specifying something like:

```
download: {
    mirrorOptions: {
      mirror: 'https://github.com/castlabs/electron-releases/releases/download/'
    }
}
```

In your config.

**Comment by olirehacek** [comment]
> If you read the docs for electron-builder you should find there's a way to configure it with mirror options. It'll means specifying something like:
> 
> ```
> download: {
>     mirrorOptions: {
>       mirror: 'https://github.com/castlabs/electron-releases/releases/download/'
>     }
> }
> ```
> 
> In your config.

Yes, I have system wide variable ELECTRON_BUILDER_BINARIES_MIRROR, ELECTRON_MIRROR set to the castlabs GitHub repo, but that does not seems to do the trick.

**Comment by simongregory** [comment]
Not sure I can add anymore, if you've got the config right then it sounds like there's a bug to raise elsewhere. I don't use electron-builder, but I'm pretty sure what I'm using delegates to the same package (and that works here), might be worth you checking then reading the usage docs: https://github.com/electron/get#usage

**Comment by olirehacek** [comment]
> Not sure I can add anymore, if you've got the config right then it sounds like there's a bug to raise elsewhere. I don't use electron-builder, but I'm pretty sure what I'm using delegates to the same package (and that works here), might be worth you checking then reading the usage docs: https://github.com/electron/get#usage

Appreciate the fast reply Simon,
Can you recommend other packaging solution that is working with castlabs electron ?

**Comment by khwaaj** [comment]
I can't really exactly but I think they moved this option at some point. Anyway, you need to include it under `build` in your `package.json` and add an extra `v` compared to the above URL. E.g. something like this:
```
{
  "name": "MyApp",
  ...,
  "build": {
    "electronDownload": {
      "mirror": "https://github.com/castlabs/electron-releases/releases/download/v"
    },
    ...,
    "afterPack": "build/after-pack.js",
    "afterSign": "build/after-sign.js"
  }
}
```

It might work with environment variables too, but I've not tested that.

**Comment by olirehacek** [comment]
> I can't remember exactly but I think they moved this option at some point. Anyway, you need to include it under `build` in your `package.json` and add an extra `v` compared to the above URL. E.g. something like this:
> 
> ```
> {
>   "name": "MyApp",
>   ...,
>   "build": {
>     "electronDownload": {
>       "mirror": "https://github.com/castlabs/electron-releases/releases/download/v"
>     },
>     ...,
>     "afterPack": "build/after-pack.js",
>     "afterSign": "build/after-sign.js"
>   }
> }
> ```
> 
> It might work with environment variables too, but I've not tested that.

Emil, yet again you are absolute lifesaver. The "v" and the end of the url was the issue.
