### ISSUE TITLE
Dowload 404 Error

### ISSUE THREAD

**Issue by SachinParankush** [castlabs/electron-releases#66]
During the npm run build console throwing error 404 

build

  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=10.0.1-wvvmp appOutDir=dist\win-unpacked
  ⨯ cannot resolve https://github.com/electron/electron/releases/download/v10.0.1-wvvmp/electron-v10.0.1-wvvmp-win32-x64.zip: status code 404
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:207
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:79
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:191
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:171
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:71
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:67
runtime.goexit
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337

**Comment by khwaaj** [comment]
You are using `electron-builder` without specifying a mirror for it to download the Electron for Content Security releases, so it is trying to download them from the wrong place. You'll need to add a `build` section to your `package.json`, i.e. something like this:

```
"build": {
  "electronDownload": {
    "mirror": "https://github.com/castlabs/electron-releases/releases/download/v"
  }
}
```

Alternatively you can point it to an already downloaded distribution, like the one installed in `node_modules` by `npm`:

```
"build": {
  "electronDist": "node_modules/electron/dist"
}
```

More information about the available configuration options for `electron-builder` can be found [here](https://www.electron.build/configuration/configuration).

**Comment by SachinParankush** [comment]
Thank you for your help.

Have a great day, cheers :)
