### ISSUE TITLE
Error while creating a build

### ISSUE THREAD

**Issue by vipul-vinsol** [castlabs/electron-releases#67]
Hey, I was trying to create a build with electron-builder,  
  
`"devDependencies": {`  
 `"electron": "`[`https://github.com/castlabs/electron-releases.git#v10.0.0-wvvmp`](https://github.com/castlabs/electron-releases.git#v10.0.0-wvvmp)`",`  
 `"electron-builder": "^22.8.0"`  
 `}`

 Scripts   
`"scripts": {`  
 `"start": "electron .",`  
 `"mac": "electron-builder -m",`  
 `"win": "electron-builder -w"`  
`}`

Build Instructions  
`"build": {`  
 `"appId": "akhil-test",`  
 `"directories": {`  
 `"buildResources": "."`  
`}, "win": {`  
 `"publish": [`  
 `"github"`  
 `],`  
 `}`  
`}`

  Error

```

electron-builder -w  ΓÇó electron-builder  version=22.8.0 os=10.0.10586
  ΓÇó loaded configuration  file=package.json ("build" field)
  ΓÇó packaging       platform=win32 arch=x64 electron=10.0.0-wvvmp appOutDir=dist\win-unpacked
  Γ¿» cannot resolve https://github.com/electron/electron/releases/download/v10.0.0-wvvmp/electron-v10.0.0-wvvmp-win32-x64.zip: status code 404
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:223
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:114
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:68
```

Thank you for your help :)

**Comment by vipul-vinsol** [comment]
@khwaaj Sir, is there a way to make a non production build. We just want to test once with an build and are still in the process of getting a license. Without that the signing key, we get error in the build we are making on license delievery

**Comment by vipul-vinsol** [comment]
I have also looked at the EVS service, I was trying to sign my app by using the command `python3 -m castlabs_evs.vmp sign-pkg --persistent path/to/app`. Can you please tell what is the meaning of the "path to app" here. We are using electon-builder and the EVS documentation mentions some hook but we can't find it. Can you help us with some example. It will be extremely helpful.

**Comment by khwaaj** [comment]
> We should add this to the readme, as this seems like a critical step in working with this version of electron

Indeed, this is a recurring question. I've been considering creating a FAQ on the Wiki and this is definitely a good candidate for an entry there.

> @khwaaj Sir, is there a way to make a non production build. We just want to test once with an build and are still in the process of getting a license. Without that the signing key, we get error in the build we are making on license delievery

I'm not completely sure I follow your meaning but if you want to use production VMP signatures during development you can sign the build installed by `npm` in `node_modules/electron/dist`. For example, if you are using our [new signing service](https://github.com/castlabs/electron-releases/wiki/EVS):

`python -m castlabs_evs.vmp sign-pkg node_modules/electron/dist`

**Comment by vipul-vinsol** [comment]
`python -m castlabs_evs.vmp sign-pkg node_modules/electron/dist` this didn't work.  
  
Error  
  
`Traceback (most recent call last):`  
 `File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main`  
 `"__main__", mod_spec)`  
 `File "/usr/lib/python3.7/runpy.py", line 85, in _run_code`  
 `exec(code, run_globals)`  
 `File "/usr/local/lib/python3.7/dist-packages/castlabs_evs/vmp.py", line 20, in <module>`  
 `from cryptography.x509 import load_der_x509_certificate, ObjectIdentifier`  
 `File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 7, in <module>`  
 `from cryptography.x509.base import (`  
 `File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 15, in <module>`  
 `from cryptography.x509.extensions import Extension, ExtensionType`  
 `File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 19, in <module>`  
 `from cryptography.hazmat.primitives import constant_time, serialization`  
 `File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>`  
 `from cryptography.hazmat.bindings._constant_time import lib`  
`ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._constant_time'`

**Comment by khwaaj** [comment]
The `path/to/app` part means the path to the directory containing your application, e.g. the directory that contains `Electron.app` or `electron.exe` in case you have not renamed the application. This is a bit unclear in the documentation and is on my TODO to update.

You can read more about the [hooks](https://www.electron.build/configuration/configuration#hooks) in the documentation for `electron-builder`. I don't currently have complete examples but have plans add a sort of "quick start" when I get the time to do it.

**Comment by khwaaj** [comment]
You are missing required modules for some reason, did you follow the instructions when you installed the EVS module? Or did you perhaps use a virtual environment and forget to activate it?

**Comment by vipul-vinsol** [comment]
@khwaaj We have tried \``python -m castlabs_evs.vmp sign-pkg dist/ulesson.exe` which is the `.exe` we got from electon-builder. This also failed, I am getting the error in a second

**Comment by vipul-vinsol** [comment]
No, we did as the instructions said, `python3 -m pip install --upgrade castlabs-evs`

**Comment by khwaaj** [comment]
Ok, maybe you have 2 different python 3 installations, use `python3` in your command-lines instead of `python`.

**Comment by khwaaj** [comment]
> @khwaaj We have tried ``python -m castlabs_evs.vmp sign-pkg dist/ulesson.exe` which is the `.exe` we got from electon-builder. This also failed, I am getting the error in a second

You cannot sign the `.exe` directly with `sign-pkg`, just pass `dist/`.

**Comment by vipul-vinsol** [comment]
Here is the steps I am following, please suggest if there is some error  
 `python -m castlabs_evs.vmp sign-pkg node_modules/electron/dist`  
`npm run build win` -> this builds the exe

**Comment by khwaaj** [comment]
Try `python3` instead of `python` in your first command line, like I suggested above, so that you are matching what you did during install. Not sure it will help, but something is clearly not right in your python environment.

If that doesn't help you can try to re-install `castlabs-evs`, e.g:

`python3 -m pip uninstall castlabs-evs`
`python3 -m pip install castlabs-evs`

I guess it could be that you have an old `cryptography` module installed, since before, that makes things go haywire. I'll se about adding a version constraint to `castlabs-evs` for `rc2` too to make sure that a recent version is used. In the meantime you can try to upgrade it manually:

`python3 -m pip install --upgrade cryptography`

**Comment by vipul-vinsol** [comment]
```
$ python -m castlabs_evs.vmp sign-pkg --persistent ./dist/
Signing: ./dist\ulesson-desktop-poa Setup 1.0.0.exe
Verifying any existing VMP signature
- Signature invalid: Failed to decode signature
Requesting VMP signature
HTTPError: Signing request failed: 400 Bad Request
<- ValidityError: Binary signature denied
```

@khwaaj Hey some success here, but got this error this time

**Comment by khwaaj** [comment]
That is the way it should look, so progress! `ValidityError: Binary signature denied` means that you are trying to sign an unsupported binary, i.e. not one of your Electron for Content Security releases or one older than `v6`.

**Comment by vipul-vinsol** [comment]
```

{
 "name": "ulesson-desktop-poa",
 "version": "1.0.0",
 "description": "POA for uLesson Desktop",
 "main": "main.js",
 "scripts": {
   "start": "electron .",
   "mac": "electron-builder -m",
   "win": "electron-builder -w",
   "build": "electron-builder -mwl"
 }
 
 
 ,
 "build": {
   "appId": "akhil-test",
   "electronDist": "node_modules/electron/dist",
   "directories": {
     "buildResources": "."
   },
   "mac": {
     "publish": [
       "github"
     ],
     "category": "public.app-category.productivity"
   },
   "win": {
     "publish": [
       "github"
     ]
   },
   "linux": {
     "publish": [
       "github"
     ],
     "category": "Network"
   }
 },
 "keywords": [],
 "author": "Vipul Bhardwaj <vipulsworkmail@gmail.com> (vipulbhj.github.io)",
 "license": "MIT",
 "devDependencies": {
   "debug-menu": "^0.6.1",
   "electron": "https://github.com/castlabs/electron-releases.git#v10.0.0-wvvmp",
   "electron-builder": "^22.8.0"
 },
 "dependencies": {
   "electron-debug": "^3.1.0"
 }
}
```

**Comment by vipul-vinsol** [comment]
```

{
 "name": "ulesson-desktop-poa",
 "version": "1.0.0",
 "description": "POA for uLesson Desktop",
 "main": "main.js",
 "scripts": {
   "start": "electron .",
   "mac": "electron-builder -m",
   "win": "electron-builder -w",
   "build": "electron-builder -mwl"
 }
 
 
 ,
 "build": {
   "appId": "akhil-test",
   "electronDist": "node_modules/electron/dist",
   "directories": {
     "buildResources": "."
   },
   "mac": {
     "publish": [
       "github"
     ],
     "category": "public.app-category.productivity"
   },
   "win": {
     "publish": [
       "github"
     ]
   },
   "linux": {
     "publish": [
       "github"
     ],
     "category": "Network"
   }
 },
 "keywords": [],
 "author": "Vipul Bhardwaj <vipulsworkmail@gmail.com> (vipulbhj.github.io)",
 "license": "MIT",
 "devDependencies": {
   "debug-menu": "^0.6.1",
   "electron": "https://github.com/castlabs/electron-releases.git#v10.0.0-wvvmp",
   "electron-builder": "^22.8.0"
 },
 "dependencies": {
   "electron-debug": "^3.1.0"
 }
}
```

**Comment by vipul-vinsol** [comment]
I work for vinsol, uLesson is our client. We are build an electron desktop app for them
Here are the commands we are using
* npm run win
* python -m castlabs_evs.vmp sign-pkg --persistent ./dist/

Getting the error from the second command

**Comment by vipul-vinsol** [comment]
> That is the way it should look, so progress! `ValidityError: Binary signature denied` means that you are trying to sign an unsupported binary, i.e. not one of your Electron for Content Security releases or one older than `v6`.
> 
> Btw, is `ulesson-desktop-poa Setup 1.0.0.exe` really your app or something else? If you have multiple executables in the package directory you may need to provide a name hint to `sign-pkg`.

Yes that is the executable we are trying to sign. electron-builder is generating some extra files, I am not sure what are they

**Comment by khwaaj** [comment]
Looking at the logs the executable you are trying to sign is too small to be our `v10.0.0-wvvmp` release. If you check the file `node_modules/electron/dist/version`, what does it say?

I just successfully used `electron-builder` with `v10.0.0-wvvmp` on `win32-ia32` with `EVS`, which matches what you are trying to do, so there is something we are missing here.

**Comment by vipul-vinsol** [comment]
@khwaaj Can you share the `package.json` you used. I have checked the version and it says 10.0.0 here is a screenshot of the same. Can you share the example which you were able to get working please. We have a very small demo, I can send you the code via a zip if you want  
 

![](https://user-images.githubusercontent.com/50447641/92233085-431e7f80-eecd-11ea-86ec-7b0b22cd4a3f.png)

**Comment by vipul-vinsol** [comment]
@khwaaj We just discovered that the unpacked version of the app is indeed signed. But that's not the installer, I think this is the problem that you mentioned regarding multiple files in our dist folder. I am not sure what is happening here, but we want to be able to make an installer which will install the signed `.exe`  
  
Were you able to get an installer working ??

**Comment by khwaaj** [comment]
You don't need to sign the installer at all, only electron package before the installer is assembled, e.g. using the `hooks` I mentioned. Since you have signed `node_modules/electron/dist` already it might work without using the `hooks` at  all, depending on how you configured `electron-builder`, but things like adding an icon or other meta-data will break the VMP signature on Windows and require that you re-sign the unpacked version in a `hook`, before it is archived into an installer.

**Comment by vipul-vinsol** [comment]
Hey @khwaaj, thank you for your help, we got it working. From our initial testing, we have observed something interesting, when we use persistent license option, two calls for the license are made and both with different `clientId` which seems to change on subsequent requests.   
  
This doesn't seem to happen when we use online, without electron.   
  
Any ideas on why is this happening, can these be since one is for playing and other one is for storing.  
Thank you for your help :)

**Comment by khwaaj** [comment]
Good to hear you got it working!

That is interesting, we are actually investigating something similar to this in another context which might be related. To clarify, this happens with a `persistent` VMP signature in electron but not with a `streaming` signature? Or was it that this doesn't happen in Chrome, when online, but always happens in electron regardless of the signature type? If that is the case, it would be interesting to know which CDM version is installed in both cases as there have apparently been some changes around the `clientId` between versions.

**Comment by khwaaj** [comment]
Never mind the talk about `persistent`/`streaming` signatures above, I was still en EVS-mode. It was pointed out to me that you were probably talking about persistent vs non-persistent sessions, which makes far more sense. It also aligns better with the other issue we are investigating. I'll keep you posted.

**Comment by bansalakhil** [comment]
@khwaaj @vipul-vinsol I think this issue can be closed. As we were able to create our build.

**Comment by khwaaj** [comment]
Good to hear, I'll close this then.
