### ISSUE TITLE
Spotify Connect issues, wondering if EVS is involved...

### ISSUE THREAD

**Issue by jimfarley** [castlabs/electron-releases#69]
I've been trying out the awesome new EVS service to sign my Electron app that includes a Spotify player.  Shortly after starting to test it with an EVS-signed app, after all was working just fine for a day or so, I was suddenly unable to Spotify Connect to any devices that were running behind my wifi (including desktop apps on two different laptops, Spotify Web App devices running in my Electron app, and a set of Echo devices on the same network).  After some testing I found that I was able to Connect devices on other networks (like my mobile phone app, or a desktop app connected via a 4G network).  On my Electron app, the API errors I received for the Connect requests said the action was "Forbidden", reason was "UNKNOWN".

This issue went away yesterday (after about 4 days of errors), then came back today, and right now as I type this it seems to have corrected itself again.

The timing might be coincidence, but I'm wondering if the EVS-signed app making a Connect request (and/or streaming transactions) could be triggering something.  E.g., could Spotify have mis-diagnosed the Web Player running in the EVS-signed app as a rogue Spotify device and blacklisted my wifi region (or the subnet it falls into within my network provider)?

**Comment by khwaaj** [comment]
I'm not entirely clear on if this is this something that has been working previously, before you started to use EVS?

Anyway, I highly doubt this has anything to do with EVS or the VMP-signing itself, at least not directly. We are using the standard Widevine CDM, and EVS VMP-signs the application with official VMP certificates that have been thoroughly verified to work with commercial streaming services.

That said, I'm not familiar with the Spotify SDK, and I have no idea if Spotify is employing some heuristics to try and catch rouge clients and block them from using the service. If they do, I suppose it is possible that such an algorithm could mistakenly identify a new client as a bad actor, but I think it is more likely something else is the problem. 

From my, fairly limited, experience as a user of Spotify Connect I'm not really impressed with the stability in my environment (including some Sonos speakers and other Android based devices). I've seen it stop working for no apparent reason, taking forever to get back into working order. I've never really put the effort in to try and diagnose it, but it appears to be intermittent so it could just be that temporary instabilities can manifest in the architecture powering Spotify Connect. Or maybe that it somehow clashes with certain network topologies.

Maybe someone else with more insight into how Spotify Connect works have some ideas that can share?

**Comment by jimfarley** [comment]
Yes, this was all working before without issues.  The only delta in our code was re-enabling the Spotify Web Player option in the app, and EVS signing the app.  

Everything you are saying makes sense, and that line of thinking made me think it's likely some erroneous traffic characterization by Spotify that is triggering an auto-blacklist of some kind.  The fact that the failures were limited to devices running behind our wifi network makes me think it is localized somehow, rather than a general Spotify outage of some kind.

If anyone has any further insights to offer, they would be appreciated.  This could all be coincidence and something else entirely is amiss at Spotify.  But if it is somehow related to EVS-signed clients "rubbing Spotify the wrong way" somehow, it would be in all our interests to get to the bottom of it.  Thanks in advance...

**Comment by jimfarley** [comment]
Quick followup on this, in case it's useful to others.  This issue has recurred a few more times for very brief intervals in our testing (minutes rather than days/hours), but generally seems to have "fixed itself" and we haven't seen a recurrence in a few days now.  Very likely this is just the latest quirkiness in Spotify's Connect services and the EVS introduction was coincidence, but heads up in case other EVS apps encounter this.
