### ISSUE TITLE
electron-v1.8.2-vmp1010-win32-ia32 crashing

### ISSUE THREAD

**Issue by tbeloqui** [castlabs/electron-releases#7]
- Electron version: v1.8.2-vmp1010
- Operating system: Windows 10 Pro x64 (1709)
- Node version: v8.9.4

**# Expected behaviour**
Electron should run normally

**# Actual behavior**
It crashes when running on the electron-quick-start example.
Exit status is 3221225595

**# How to reproduce**
Tested using a slighlty modified electron-quick-start example.
Performed this change on the example: https://github.com/tbeloqui/electron-quick-start/commit/433c12467888e9cdfff804fdcbcc969cd1d1e544

```
git clone https://github.com/tbeloqui/electron-quick-start
cd electron-quick-start
npm install
npm start
```

**Comment by khwaaj** [comment]
Thanks for your report. I've been able to reproduce your issue with the latest win32/ia32 build and I'll look into correcting it. The previous build, 1.8.2-beta.5, does work though, and uses the same codebase as 1.8.2 stable, except for some meta-data changes, so if you need to continue working I would recommend falling back to that for the time being.

**Comment by khwaaj** [comment]
I've updated the 1.8.2 release with a re-packaged zip for win32/ia32, which fixes the issue. For the new zip to be installed correctly please make sure to clear the electron-download cache files (resides in ~/.electron/ by default).

**Comment by tbeloqui** [comment]
Works fine now :), thank you very much @khwaaj !
