### ISSUE TITLE
Code Repository has No License

### ISSUE THREAD

**Issue by JeffCarpenter** [castlabs/electron-releases#72]
There is no LICENSE.txt or md file stating which license this code is available under

**Comment by khwaaj** [comment]
Although this repo doesn't actually contain the Electron source code anything available here is under the same license as Electron itself - the MIT License. I'll see about adding license file stating this, thanks for pointing it out!

Also, the release packages already includes a license file stating this.

**Comment by khwaaj** [comment]
The repository now advertises that it is under the MIT license, so I'll go ahead and close this.
