### ISSUE TITLE
Apple Silicon / macOS Big Sur Support (Discussion)

### ISSUE THREAD

**Issue by olirehacek** [castlabs/electron-releases#76]
Hi Guys,

As the new MACs are ARM-based I am opening the discussion about support for Apple Silicon.
Electron currently has darwin-arm64 build that is running under Apple Silicon - https://www.electronjs.org/blog/apple-silicon

Do we have any news regarding running the Widevine under ARM Mac ? Is that something You are considering in the future?
Thanks !

**Comment by khwaaj** [comment]
Hi Ondrej,

We are aware of the new Apple hardware and this is is something we are planning to support. I know the Widevine team is working on a `darwin-arm64` CDM, so once that is available we will look into what it takes to get ECS and EVS working on the new platform.

**Comment by olirehacek** [comment]
Thanks Emil !,

Just a note: Can at least confirm that our app is functioning on Big Sur (x86).
