### ISSUE TITLE
Patching Chromium

### ISSUE THREAD

**Issue by toschlog** [castlabs/electron-releases#83]
I'm using Electron for Content Security for a video player project in which I'm performing some processing on the audio.  To get my stuff to work, I need to patch Chromium inside of Electron inside of ECS.  Is there any way to do this?

Thanks.

**Comment by khwaaj** [comment]
I'm afraid that is a bit more complicated than just using ECS, although it is possible.

We are only providing ECS as-is and custom extensions beyond that will require a commercial agreement with castLabs to either implement the feature for you or to certify an implementation of your own through the Widevine [3PL](https://github.com/castlabs/electron-releases/wiki/EVS#3pl) program. If you are interested in knowing more about this you are welcome to contact us for more details.
