### ISSUE TITLE
Failed to Install Widevine Components

### ISSUE THREAD

**Issue by RohanVDeshpande** [castlabs/electron-releases#84]
I re-packaged my app today (as normal). After running the installer, I got the following error on app launch:

> Failed to install Widevine components. Error No update necessary.
![image](https://user-images.githubusercontent.com/13295235/103103062-211c4a80-45ed-11eb-8c29-bd95aa284fb8.png)

Does anyone know what might be causing this?
I also tried disabling Widevine update using:
`app.commandLine.appendSwitch('no-update-widevine-cdm')`
but I'm still getting the same error.

**Comment by RohanVDeshpande** [comment]
Woops. It turns out that another (seemingly unrelated) issue was causing startup to fail. Abnormal termination was causing a misleading error message. The issue is not with castlabs electron/widevine...

**Comment by JeremiahUL** [comment]
Thanks. @RohanVDeshpande This actually helped me
