### ISSUE TITLE
Is Mac 10.9 supported?

### ISSUE THREAD

**Issue by simongregory** [castlabs/electron-releases#9]
A week ago we started shipping our app based on v1.8.3-vmp1010 to Mac users. We've since received a number of complaints from users saying that they're unable to run the app and are getting a message advising them to check the app is compatible with their version of the OS (Mac 10.9).

More technical users have supplied logs, which suggests the app is looking for, and not finding, the CoreBluetooth.framework  (which is referenced from the Electron Framework, and I think Mac 10.10 and above only):

`Dyld Error Message:  Library not loaded: /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth`

A little digging in the Electron v1.8.x branch (ie [brightray.gyp](https://github.com/electron/electron/blob/1-8-x/brightray/brightray.gyp)) didn't highlight any references to the framework. Before I dug any deeper I wanted to make sure that the CoreBluetooth library wasn't a requirement for the Castlabs Electron build.

**Comment by simongregory** [comment]
Thanks for the quick response @khwaaj - I'll find a 10.9 machine and try the stock Electron and let you know.

**Comment by khwaaj** [comment]
Ok, it seems that our build of the Electron Framework indeed does have a dependency on CoreBluetooth. I checked stock Electron 1.8.3 which does not have this dependency, so there is a difference here, and you'll likely find that it will indeed run on macOS 10.9.

I'll try to dig into this further to see if I can figure out what is going on.

**Comment by simongregory** [comment]
Unfortunately I'm still trying to source a 10.9 machine.

I've only just noticed the request for extra info on the binary, this is all the log info I have: 

`Process: Downloads [815] Path: /Applications/Downloads.app/Contents/MacOS/Downloads Identifier: uk.co.downloads Version: ??? Code Type: X86-64 (Native) Parent Process: launchd [150] Responsible: Downloads [815] User ID: 501 Date/Time: 2018-04-02 16:02:04.156 +0100 OS Version: Mac OS X 10.9.5 (13F1911) Report Version: 11 Anonymous UUID: CDAF7FCE-C908-BFF6-56DC-935027FAEDB6 Sleep/Wake UUID: 6D13D332-EF86-4B0F-B790-3BCBB6D665EB Crashed Thread: 0 Exception Type: EXC_BREAKPOINT (SIGTRAP) Exception Codes: 0x0000000000000002, 0x0000000000000000 Application Specific Information: dyld: launch, loading dependent libraries Dyld Error Message:  Library not loaded: /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth  Referenced from: /Applications/Downloads.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework  Reason: image not found Binary Images:  0x7fff69083000 - 0x7fff690b6887 dyld (239.5) <1D3130FE-FE7E-3C4C-8E74-EB51895B6BA5> /usr/lib/dyld  0x7fff82667000 - 0x7fff82ab5fef com.apple.VideoToolbox (1.0 - 1273.57) <AA4D613A-1066-3E85-8BE0-7806566652B4> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox  0x7fff85751000 - 0x7fff85751fff com.apple.quartzframework (1.5 - 1.5) <3B2A72DB-39FC-3C5B-98BE-605F37777F37> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz  0x7fff85fc3000 - 0x7fff85fc3fff com.apple.ApplicationServices (48 - 48) <3E3F01A8-314D-378F-835E-9CC4F8820031> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices  0x7fff86021000 - 0x7fff86084ffb com.apple.SystemConfiguration (1.13.1 - 1.13.1) <339A2A90-DA25-33AF-88E5-2FB38A758FEE> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration  0x7fff86417000 - 0x7fff86468ff7 com.`

**Comment by khwaaj** [comment]
Thanks, that points to Electron Framework, which matches what I found. I'm fairly certain I know what the issue is here. There appears to be some macOS SDK mismatch going on on the build machine so I've made some adjustments and will rebuild 1.8.4 to see if the CoreBluetooth dependency is gone.

If this works I'll update the 1.8.4 release to use the rebuilt package. Is this good enough for your purposes or do you need 1.8.3 specifically for your fix?

**Comment by simongregory** [comment]
I'd prefer 1.8.4 so a build for that works for us - thanks!

**Comment by khwaaj** [comment]
Great, I'll notify you once I have posted the release. Provided nothing goes wrong with the build or testing that will likely be sometime tomorrow.

**Comment by khwaaj** [comment]
I just posted an updated 1.8.4 release. Make sure to clear any electron-downloader caches when upgrading to avoid the old release being used.

I've not actually been able to test this release on 10.9, since I don't have access to a system using it, but the CoreBluetooth dependency is gone from Electron Framework so I'm pretty confident that the issue has been adressed. Please let me know how it goes!

**Comment by simongregory** [comment]
Thanks @khwaaj, that's enabled me to get a new build ready. I am expecting to have it tested on 10.9 early tomorrow so will confirm all is ok then.

**Comment by simongregory** [comment]
Early indications show the new build is working on 10.9. Thanks again!
