### ISSUE TITLE
HBO Max Service Error Even after using VMP Signing Service. Netflix works fine.

### ISSUE THREAD

**Issue by ryankashi** [castlabs/electron-releases#92]
Hi everyone!

I just tried out my application for the first time today using HBO Max, however I am getting this error:

Service error:
H-25e9b383-fb97-4707-8ac9-f88935070383

Netflix works fine inside of my application for both development as well as packaged versions, however HBO Max is giving me this error. I have tested on both Electron versions 9.4.3 as well as 12.0.4. I am almost certain that this is a Widevine problem with castlabs. I am using the vmp signing service to sign my application.

Thanks!

**Comment by ryankashi** [comment]
It appears that Brave Browser also incorporates Widevine for their viewership, of which works with HBO Max. Brave, similar to electron, is built on top of Chromium so shouldn't there be a way for Electron to work with HBO Max as well?

**Comment by stcrestrada** [comment]
Did you figure this out?

**Comment by ryankashi** [comment]
Yes I did! It was an issue with my electron code, not Castlabs!

**Comment by markelrod** [comment]
@ryankashi - we are having a similar issue. Can you please tell us how you fixed it? Thanks!
